<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsPurchaseOrder
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
if($block->getPoDocument()){?>
	
	 <div class="image_box">
			 <a href="<?php echo $block->getFileSrc().$block->getPoDocument()?>" target="_blank"><?php echo $block->getPoDocument()?></a>
     </div>
	
<?php }


?>
<style>
.image_box > img {
    float: left;
    margin-right:10px;
}
</style>
