<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php /** @var \Ced\CsOrder\Block\Order\View\Totals $block */ ?>
<?php
$vorder = $block->getVorder();
$_order = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $block->getFullTaxInfo();
?>
<div class="order-totals">
    <table width="100%" cellspacing="0">
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Grand Total (Earned)') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getBaseOrderTotal(),
                        $vorder->getOrderTotal(),
                        false,
                        ''
                    ); ?>
                </strong>
            </td>
        </tr>
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Commission Fee') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getShopCommissionBaseFee(),
                        $vorder->getShopCommissionFee(),
                        false,
                        ' '
                    ); ?>
                </strong>
            </td>
        </tr>
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Net Earned') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getBaseOrderTotal() - $vorder->getShopCommissionBaseFee(),
                        $vorder->getOrderTotal() - $vorder->getShopCommissionFee(),
                        false,
                        ' '
                    ); ?>
                </strong>
            </td>
        </tr>
    </table>
</div>
