<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<meta http-equiv="Content-Type" content="<?= /* @noEscape */  $this->getContentType() ?>" />
<title><?= /* @noEscape */  $this->getTitle() ?></title>
<meta name="description" content="<?= /* @noEscape */  htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?= /* @noEscape */  htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?= /* @noEscape */  htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?= /* @noEscape */  $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?= /* @noEscape */  $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
	<script type="text/javascript">
	//<![CDATA[
	    var BLANK_URL = '<?= /* @noEscape */  $this->helper('core/js')->getJsUrl('blank.html') ?>';
	    var BLANK_IMG = '<?= /* @noEscape */  $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
	//]]>
	</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?= /* @noEscape */  $this->helper('core/js')->getTranslatorScript() ?>
<?= /* @noEscape */  $this->getIncludes() ?>
