<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var $block \Ced\CsOrder\Block\Order\Creditmemo\Create\Adjustments */
$_source  = $block->getSource();
?>
<?php if ($_source): ?>
    <tr>
        <td class="label"><?= /* @noEscape */ $block->getShippingLabel() ?>
            <div id="shipping_amount_adv"></div>
        </td>
        <td>
            <input type="text"
                   name="creditmemo[shipping_amount]"
                   value="<?= /* @noEscape */ $block->getShippingAmount()?>"
                   class="input-text admin__control-text not-negative-amount"
                   id="shipping_amount" />
        </td>
    </tr>
<?php endif; ?>
