<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<div class="block block-account"> 
<?php if($this->getTitle()): ?>
 	<div class="block-title">
        <strong><i class="fa fa-pencil-square-o"></i><span style="margin-left : 8px;"><?= $this->getTitle() ?></span></strong>
    </div>
<?php endif ?>
<div class="block-content">
<?php if(!empty($tabs)): ?>
<ul id="<?= $this->getId() ?>" class="tabs">
<?php $i=0;$count=count($tabs);?>
<?php foreach ($tabs as $_tab): ?>
<?php $i++;?>
<?php if (!$this->canShowTab($_tab)): continue;  endif; ?>
    <li class="<?php if($count==$i) echo "last";?>" <?php if($this->getTabIsHidden($_tab)): ?>  style="display:none"<?php endif; ?>>
        <a href="<?= $this->getTabUrl($_tab) ?>" 
        	id="<?= $this->getTabId($_tab) ?>" 
        	name="<?= $this->getTabId($_tab, false) ?>" 
        	title="<?= $this->getTabTitle($_tab) ?>" 
        	class="tab-item-link <?= $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $_tab->getClass())) {?> notloaded<?php }?>">
            <span>
            	<i style="margin-right: 8px;" class="fa fa-file-text-o"></i>
            	<span class="changed" 
            		title="<?= __('The information in this tab has been changed.') ?>">
            	</span>
            	<span class="error" 
            		title="<?= __('This tab contains invalid data. Please solve the problem before saving.') ?>">
            		</span>
            		<?= $this->getTabLabel($_tab); ?>
            </span>
        </a>
        
        <div id="<?= $this->getTabId($_tab) ?>_content" style="display:none;"><?= $this->getTabContent($_tab) ?></div>
    </li>
<?php endforeach; ?>
</ul>
</div>
</div>
<?php endif; ?>
<script type="text/javascript">
    <?= $this->getJsObjectName() ?> = new varienTabs('<?= $this->getId() ?>', '<?= $this->getDestElementId() ?>', '<?= $this->getActiveTabId() ?>', <?= $this->getAllShadowTabs()?>);
</script>