<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?= $block->getChildHtml('info') ?>
<div class="order-details">
    <?= $block->getChildHtml('order_items') ?>
</div>
<script type="text/javascript">window.print();</script>
<style type="text/css">
    @media print {
        a[href]:after {
            content: none !important;
        },
        body{
            transform: scale(0.54);
            -webkit-transform: scale(0.54);
            -moz-transform: scale(0.54);
            -o-transform:  scale(0.54);
            -ms-transform:  scale(0.54);
        }
        @page {
            size: A4 portrait;
        }
    }

    .page-print .nav-toggle {
        display: none;
    }

    .page-wrapper {
        margin-left: 0px !important;
        width: 100%  !important;
</style>
