<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
<?= /* @noEscape */ $block->getChildHtml('info') ?>
<div class="row">
	<div class="order-details col-md-12">
	    <?= /* @noEscape */ $block->getChildHtml('order_items') ?>
	</div>
</div>
<div class="buttons-set">
        <p class="back-link"><a href="<?= /* @noEscape */ $block->getBackUrl() ?>"><small>&laquo; </small><?= /* @noEscape */ __('Back to Orders') ?></a></p>
</div>
</div>
</div>
</div>
</div>
</div>