<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile

/** @var  $block \Ced\CsMarketplace\Block\Vreports\Vorders\ListOrders */
$collection = $this->getVordersReports();
?>

<div style="clear:both"></div>
<form id="payment_form"
	action="javascript:void( 0 );"
	enctype="multipart/form-data" method="post">
<?php if($collection){?>
<script type="text/javascript">
    require([
        "jquery",
        "jquery/ui"
    ], function($) {
        jQuery('#export_btn').show();
        jQuery('#filter_butn6').show();
        jQuery('#filter_butn12').hide();
    });
</script>
<?php }?>
<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
	    <col width="2"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
	    <col width="1"/>
		<thead>	
			<tr>
				<th class="head"><?= __('Period') ?></th>
		        <th class="head"><?= __('Orders') ?></th> 
		        <th class="head"><?= __('Sales Items') ?></th>
				<th class="head"><?= __('Total Sales') ?></th>
				<th class="head"><?= __('Total Commission') ?></th>
				<th class="head"><?= __('Net Sales') ?></th>
			</tr>		
	    </thead>
	    <tbody>
		<?php if($collection): ?>
	    <?php $_odd = ''; ?>
	    
	    <?php foreach ($collection as $_report) { ?>
	        <tr>
	            <td class="number"><?= $_report->getPeriod();	 ?></td>
	            <td class="date"><?= $_report->getOrderCount() ?></td>
				<td class="number"><?= $_report->getProductQty() ?></td>     
	            <td class="status"><?= $block->formatCurrency($_report->getOrderTotal(),false,2,null,$_report->getCurrency());?></td>
	            <td class="status"><?= $block->formatCurrency($_report->getCommissionFee(),false,2,null,$_report->getCurrency());?></td>
				<td class="number"><?= $block->formatCurrency($_report->getNetEarned(),false,2,null,$_report->getCurrency());?></td>
	        </tr>
	        <?php } ?>
			<?php else: ?>
			<tr>
				<td colspan="6">
					<div>
					<p class="not_avail"><?= __('No Report Available'); ?></p>
					</div>
				</td>
			</tr>		
			<?php endif ?>
		</tbody>
	</table>
</div>

</form>
<p class="required"><?= __('* Required Fields') ?></p>


<script type="text/javascript">
require([
    "jquery",
    "jquery/ui"
], function($){
<?php if($this->getRequest()->getActionName()=='vorders'){ ?>

filterVordersReports(2);
<?php } ?>
  
	jQuery(document).ready(function(){
	  jQuery("#payment_form").submit(function() {
				return false;
			});
	});
});	
</script>


