<?php
/**
* CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the End User License Agreement (EULA)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* https://cedcommerce.com/license-agreement.txt
*
* @category    Ced
* @package     Ced_CsMarketplace
* @author      CedCommerce Core Team <connect@cedcommerce.com>
* @copyright   Copyright CedCommerce (https://cedcommerce.com/)
* @license     https://cedcommerce.com/license-agreement.txt
*/
?>
<div id="add_new_product" title="Add Product" class="actions-split" style="display: block;width: 100%;">
    <a href="<?= /* @noEscape */ $block->getUrl('csmarketplace/vproducts/new'); ?>" id="add_new_product_link" title="Add Product" class="action-default primary add" style="float: right;color: #fff !important;background: #000 !important;">
        <span><?= /* @noEscape */ __("Add Product");?></span>
    </a>
</div>
