<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var \Ced\CsOrder\Block\Order\Shipment\View\Form $block */
$csOrderHelper = $block->getCsorderHelper();
$_order = $block->getShipment()->getOrder();
$vendorId = $block->getSession()->getVendorId();
$vorder = $block->getVorder();
?>
<?= /* @noEscape */
$block->getChildHtml('order_info') ?>
<section class="admin__page-section order-shipment-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">

        <?php /* Billing Address */ ?>
        <div class="admin__page-section-item order-payment-method">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div><?= /* @noEscape */
                    $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?= /* @noEscape */
                    __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?>
                </div>
            </div>
        </div>
        <?php
        if (is_object($vorder) && $csOrderHelper->canShowShipmentBlock($vorder)) {
            echo $block->getChildHtml('order_shipping_view');
        }
        ?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Items Shipped') ?></span>
    </div>
    <?= /* @noEscape */
    $block->getChildHtml('shipment_items') ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <?= /* @noEscape */
        $block->getChildHtml('shipment_packed') ?>

        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Shipment History') ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= /* @noEscape */
                $block->getChildHtml('order_comments') ?></div>
        </div>
    </div>
</section>
