<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php list($formHtml,$html) = $block->getSearchFormHtml(); ?>
<?= /* @noEscape */ $formHtml; ?>
<div id="order-items">
	<?= /* @noEscape */ $html; ?>
</div>
<div id="order-errors"></div>
<br/>
<div id="order-search" class="csmarketplace-order-search-items" style="display:none">
	<?= /* @noEscape */ $block->getLayout()->createBlock('Ced\CsMarketplace\Block\Adminhtml\Vpayments\Edit\Tab\Addorder\Search')->setTemplate('Ced_CsMarketplace::vpayments/edit/tab/addorder/search.phtml')->toHtml(); ?>
</div>