<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var $block \Ced\CsOrder\Block\Order\Invoice\View\Form */
$csOrderHelper = $block->getCsorderHelper();
$_invoice = $block->getInvoice();
$_order = $_invoice->getOrder();
$vorder = $block->getVorder();
?>
<?= /* @noEscape */
$block->getChildHtml('order_info') ?>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method
        <?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?> admin__fieldset-wrapper">
            <?php /*Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= /* @noEscape */
                    $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?= /* @noEscape */
                    __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?>
                </div>
                <div class="order-payment-additional">
                    <?= /* @noEscape */
                    $block->getChildHtml('order_payment_additional'); ?>
                </div>
            </div>
        </div>
        <?php
        if (is_object($vorder) && $csOrderHelper->canShowShipmentBlock($vorder)) {
            echo $block->getChildHtml('order_shipping_view');
        }
        ?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Items Invoiced') ?></span>
    </div>

    <div id="invoice_item_container" class="admin__page-section-content">
        <?= /* @noEscape */
        $block->getChildHtml('invoice_items') ?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history" style="float:left;width:48%">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Invoice History') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <?= /* @noEscape */
                $block->getChildHtml('order_comments') ?>
            </div>
        </div>

        <div id="history_form" class="admin__page-section-item order-totals" style="float:right;width:48%">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Invoice Totals') ?></span>
            </div>
            <?= /* @noEscape */
            $block->getChildHtml('invoice_totals') ?>
        </div>
    </div>
</section>
<style type="text/css">
    .label {
        color: black;
    }
</style>
