<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<div class="form-group col-md-6 rtl-active" ><label><?= /* @noEscape */ __('Websites') ?>:</label>
	<div class="input-box category">
            <?php foreach ($block->getWebsiteCollection() as $_website): ?>
            <div class="website-name">
                <input name="product[website_ids][]"  style="float:left;" value="<?= /* @noEscape */ $_website->getId() ?>" <?php if ($block->isReadonly()):?> disabled="disabled"<?php endif;?> class="checkbox website-checkbox" id="product_website_<?= /* @noEscape */ $_website->getId() ?>" type="checkbox"<?php if($block->hasWebsite($_website->getId())): ?> checked="checked"<?php endif; ?> />
                <strong><label  style="float:left;margin-left:2px;font-weight:bold;font-size: 14px;" for="product_website_<?= /* @noEscape */ $_website->getId() ?>"><?= $block->escapeHtml($_website->getName()) ?></label></strong>
                <div style="clear:both;"></div>
            </div>
            <div style="padding-left:25px" class="webiste-groups" id="product_website_<?= /* @noEscape */ $_website->getId() ?>_data">
            <?php foreach ($block->getGroupCollection($_website) as $_group): ?>
                <label><?= /* @noEscape */ $block->escapeHtml($_group->getName()) ?></label>
                <div style="clear:both"></div>
                <div style="padding-left:15px" class="group-stores">
                <table>
                <?php foreach ($block->getStoreCollection($_group) as $_store): ?>
                    <tr>
                        <td><?= /* @noEscape */ $block->escapeHtml($_store->getName()) ?></td>
                    </tr>
                <?php endforeach; ?>
                </table>
                </div>
            <?php endforeach; ?>
            </div>
            <?php endforeach; ?>
        </div>
</div>
