<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<script>
    var BASE_URL = '<?= /* @noEscape */ $block->getUrl('*') ?>';
    var FORM_KEY = '<?= /* @noEscape */ $block->getFormKey() ?>';
    var require = {
        "baseUrl": "<?= /* @noEscape */ $block->getViewFileUrl('/') ?>"
    };
</script>
