<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$vorder = $block->getCurrentVorder();
if ($vorder && $vorder->getBaseTaxAmount()) { ?>
<tr>
    <td class="a-right" colspan="9">
        <div class="summary-collapse">
            <?= /* @noEscape */ __('Tax') ?>
        </div>
    </td>
    <td class="a-right last">
        <?= /* @noEscape */ $block->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php } ?>
</tr>
