<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var $block \Ced\CsOrder\Block\Order\View\Items */
$order = $block->getRegistry()->registry('current_vorder');
$vendorId = $order->getVendorId();
$_order = $block->getOrder();
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?= /* @noEscape */
                    __('Product') ?></span></th>
            <th class="col-status"><span><?= /* @noEscape */
                    __('Item Status') ?></span></th>
            <th class="col-price-original"><span><?= /* @noEscape */
                    __('Original Price') ?></span></th>
            <th class="col-price"><span><?= /* @noEscape */
                    __('Price') ?></span></th>
            <th class="col-ordered-qty"><span><?= /* @noEscape */
                    __('Qty') ?></span></th>
            <th class="col-subtotal"><span><?= /* @noEscape */
                    __('Subtotal') ?></span></th>
            <th class="col-tax-amount"><span><?= /* @noEscape */
                    __('Tax Amount') ?></span></th>
            <th class="col-tax-percent"><span><?= /* @noEscape */
                    __('Tax Percent') ?></span></th>
            <th class="col-discont"><span><?= /* @noEscape */
                    __('Discount Amount') ?></span></th>
            <th class="col-total last"><span><?= /* @noEscape */
                    __('Row Total') ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getItemsCollection(); ?>
        <?php $i = 0;
        foreach ($_items as $_item): ?>
            <?php if ($_item->getParentItem() || $_item->getVendorId() != $vendorId) {
                continue;
            } else {
                $i++;
            } ?>
            <?php if ($i > 0): ?>
                <tbody class="<?= /* @noEscape */
                $i % 2 ? 'even' : 'odd' ?>">
                <?= /* @noEscape */
                $block->getItemHtml($_item) ?>
                <?= /* @noEscape */
                $block->getItemExtraInfoHtml($_item) ?>
                </tbody>
            <?php else: $i++; ?>
            <?php endif ?>

        <?php endforeach; ?>
    </table>
</div>
