<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile

/**
 * @var \Ced\CsMarketplace\Block\Vpayments\Stats $block
 */ 

$viewModel = $block->getData('viewModel');
$pricingHelper = $viewModel->getPricingHelper();
?>
<div class="row">
    <div class="col-md-12" style="margin-top:10px;">
        <div class="panel panel-default">
            <div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
                <div style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
                    <?= __('Transactions Statistics') ?>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12" style="margin-top:10px;">
                    <div class="order-items order-details table-responsive">
                        <table id="my-products-table" class="table table-bordered table-hover table-striped">
                            <col width="1"/>
                            <col width="1"/>
                            <col width="1"/>
                            <thead>
                            <tr style="background-color: #f5f5f5; color: #23527c;">
                                <th class="head"><?= __('Total Earned Amount') ?></th>
                                <th class="head"><?= __('Total Pending Amount') ?></th>
                                <th class="head"><?= __('Pending Transfers') ?></th>
                            </tr>
                            <thead>
                            <tbody>
                            <tr>
                                <td class="number">
                                    <span class="nobr">
                                        <?= $block->formatCurrency($block->getEarningAmount()); ?>
                                    </span>
                                </td>
                                <td class="number">
                                    <span class="nobr">
                                        <?= $block->formatCurrency($block->getPendingAmount()); ?> 
                                    </span>
                                </td>
                                <td class="status">
                                    <span class="nobr">
                                        <?= $this->getPendingTransfers() ? $this->getPendingTransfers() : 0; ?> 
                                    </span>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>