<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<div class="row">
	<div class="col-md-12 ced-transactions-details" style="margin-top:10px;"> 
		<?= $block->getFormHtml(); ?> 
	</div>
	<p class="back-link" >
		<a class="back-link" 
			href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
				<small>&laquo; </small>
				<?php echo __('Back') ?>
		</a>
	</p>
</div>
