<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
$product_id = $block->getProductId();
$vendor_id = $block->getVendor($product_id);
$product_name = $block->getProduct()->getName();
$login = $block->isCustomerLoggedIn();
$custGroups = $block->getAllowedCustomerGroups();
if(empty($login)){
    $groupId =  '0';
}
else{
    $groupId =  $block->getCustomer()->getGroupId();
}

/*customergroups=> groups allowed for RFQ*/
if (in_array($groupId, $custGroups)):
if (in_array($groupId, $custGroups)){
    $hideto = "yes";
}
else{
    $hideto = "no";
}
?>
<input type="hidden" id="hidecart" value="<?= /* @noEscape */ $hideto;?>" />
<?php $buttonTitle = /* @noEscape */ __('Add to Quote'); ?>
<?php if (in_array($groupId, $custGroups)) { ?>
    <?php if($block->getProductType() == Magento\Catalog\Model\Product\Type::TYPE_SIMPLE
        || $block->getProductType() == Magento\Catalog\Model\Product\Type::TYPE_BUNDLE
        || $block->getProductType() == 'configurable'){ ?>
        <div style="clear: both;"></div>
        <div class="box-tocart cart-to-quote">
            <div class="fieldset">
                <div class="actions">
                    <?php if(empty($login)){ ?>
                        <a href="<?= /* @noEscape */ $block->getUrl('customer/account/login') ?>">
                            <?= /* @noEscape */ __('Try login to request a quote for the product') ?>
                        </a>
                    <?php }else{ ?>
                        <button class="button btn btn-info uptransform action primary ced-to-quote"
                                title="<?= /* @noEscape */ __('Get Quote') ?>"
                                type="button" id="sendquote" name="submit" >
                            <span><span><?= /* @noEscape */ __('Get Quote') ?></span></span>
                        </button>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
<?php } ?>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        var dataForm = $('#quoteform');
        var ignore = null;
        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    });
</script>
<script>
    require([
        'jquery',
        'Ced_RequestToQuote/js/jquery.form',
    ], function($){
        $("#sendquote").click(function(){
            var id = $(this).prev().val();
            var dataForm = $('#product_addtocart_form');
            dataForm.mage('validation', {});
            if(dataForm.validation('isValid') && dataForm.validation()) {
                $.ajax({
                    type: "POST",
                    url: "<?= /* @noEscape */ $block->getBaseUrl().'requesttoquote/quotes/getsimple'?>",
                    data: dataForm.serialize(),
                    success: function(html){
                        window.ankit = html;
                        console.log(html);
                        if(html.bundle_cart_options){
                            var parent_id = $('input[name=product]').val();
                            $( "input[name*='product_id']" ).val(html.product);
                            $( "input[name*='product_name']" ).val(html.simple_product_name);
                            /*to prefill the qty field*/
                            var quote_qty = $("input[name*='quote_qty']");
                            if(!quote_qty.val())
                                quote_qty.val(html.qty);
                            var quoteform = $('#quoteform');
                            quoteform.append('<input type="hidden" name="bundle_cart_options" value="'+html.bundle_cart_options+'" />');
                            quoteform.append('<input type="hidden" name="parent_id" value="'+parent_id+'" />');
                        }else{
                        /*thorw error that unable to find bundle options*/
                        }
                        var flag =false;
                        var flag2=true;
                        var path = '<?= /* @noEscape */ $block->getUrl('requesttoquote/quotes/save'); ?>';
                        require(['jquery','Magento_Ui/js/modal/modal'], function ($,modal) {
                            var options = {
                                type: 'popup',
                                responsive: true,
                                innerScroll: true,
                                modalClass: "ced-request-to-quote-product-price-qty-popup",
                                title: 'Enter Quote Details',
                                buttons: [{
                                    text: $.mage.__('<?= /* @noEscape */ $buttonTitle ?>'),
                                    id: 'quote_submit',
                                    click: function () {
                                        var self = this;
                                        if ($('#quoteform').valid()) {
                                            $.ajax({
                                                url : path,
                                                type: "POST",
                                                showLoader: true,
                                                data : $("#quoteform").serializeArray(),
                                                success: function(data){
                                                    self.closeModal();
                                                    window.location.reload();
                                                }
                                            });
                                        }
                                    }
                                }]
                            };
                            var popup = modal(options, $('#message-content'));
                            $('#message-content').modal('openModal');
                        });
                    }
                });
            }
        });
        $('document').ready( function(){
            var hide = $('#hidecart').val();
            if(hide == 'yes'){
                $('#product-addtocart-button').remove();
            }
        });
        $(".product-options-wrapper select[id^='attribute']").on("change", function () {
            setTimeout(function () {
                var selectsValues = $(".product-options-wrapper select[id^='attribute']");
                if (selectsValues[0].value !== "" && selectsValues[1].value !== "") {
                    var configurable = $("#product_addtocart_form").data('mageConfigurable');
                    var selectedProductId = configurable.simpleProduct;
                    console.log('Selected simple product Id is: ', selectedProductId);
                }
            }, 500);
        });
    });
</script>
<?php endif; ?>
