<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsRfq
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?php

$vendorId = $block->getVendorId();
if(!$vendorId){
	echo $block->setTemplateProductWise("Ced_RequestToQuote::quotes/addtoquoteconfig.phtml")->toHtml();
}else{
	echo $this->setTemplateProductWise("Ced_CsRfq::quotes/vendor/addtoquoteconfig.phtml")->toHtml();
}
