<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?= /* @noEscape */ $block->getButtonsHtml() ?></div>
        <h4 class="fieldset-legend <?= /* @noEscape */ ($block->getHeaderCssClass()) ? $block->getHeaderCssClass().' icon-head' : '' ?>"><?= /* @noEscape */ $block->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
		<?= /* @noEscape */ $block->getLayout()->createBlock('Ced\CsMarketplace\Block\Adminhtml\Vpayments\Edit\Tab\Addorder\Search\Grid')->toHtml(); ?>
    </div>
</div>
<script type="text/javascript">
	var csaction = '';
	function addorder() {
		myArray= new Array();
		var ids = document.getElementsByClassName("csmarketplace_relation_id checkbox");
		document.getElementById('csmarketplace_vendor_total').value = 0.00;
		csaction = ''; 
		for(var i=0; i<ids.length ; i++) {
			if (ids[i].checked) {
				myArray.push(ids[i].value);
				if(csaction.length > 0) {
					csaction += ','+ids[i].value;
				} else {
					csaction = 'order_ids/'+ids[i].value;
				}		
			}
		}
		
		var csloader = new varienLoader();
		new Ajax.Updater('order-items_grid', '<?= /* @noEscape */ $block->getUrl('*/*/addOrders')?>', {
			  parameters: { 'vendor_id':document.getElementById('vendor_id').value,'order_ids[]': myArray ,'type' : <?= /* @noEscape */ $block->getRequest()->getParam('type',\Ced\CsMarketplace\Model\Vpayment::TRANSACTION_TYPE_CREDIT); ?>},
			  onComplete: function(transport) {
							document.getElementById('csmarketplace_vendor_total').value = document.getElementById('csmarketplace_fetched_total').value;
							document.getElementById("csmarketplace_add_more").style.display = "";
							document.getElementById("order-search").style.display = "none";
						},
			});
	}
</script>
