<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
    $params = $this->_getSession()->getData('vproducts_reports_filter');
    $params["website_id"] = $this->_storeManager->getStore()->getWebsiteId();
?>

<form action="javascript:void( 0 )" class="product-reports" method="post" id="report-form-validate" width="100%">
	<div class="col-md-12">
		<h4 class="legend"><?= __('Filter Report') ?></h4>
        <!-- Create Website filter -->
        <div class="form-group col-md-4">
            <label for="website_id"><?=__('Website:') ?></label>
            <div class="input-box">
                <?php
                $websites = $block->getWebsites();
                if (count($websites) > 1) {
                    $websiteId = $params['website_id'];
                    if (!$websiteId) {
                        $websiteId = $block->getDefaultWebsiteId();
                    }
                    ?>
                    <select name="website_id" id="website_id" class="form-control">
                        <?php foreach ($websites as $key => $website) { ?>
                            <option value="<?= $key ?>"
                                <?php if ($websiteId == $key) { ?>
                                    selected="selected"
                                <?php } ?>>
                                <?= $website ?>
                            </option>
                        <?php } ?>
                    </select>
                    <?php
                } else {
                    $website = current($websites);
                    ?>
                    <input type="hidden" name="website_id" value="<?= array_key_first($websites) ?>" />
                    <span><?= reset($websites) ?></span>
                    <?php
                }
                ?>
            </div>
        </div>
        <!-- End Website filter -->
		<div class="form-group col-md-4">
			<label class="required"><em>*</em><?= __('Start date') ?>:</label>
			<div class="input-box" id="from-container">
				<input type="text" class="required required-entry input-text validate-date form-control"
                       name="from" id="from"
                       value="<?= isset($params['from']) && ($params['from']!="")?$params['from']:""; ?>"/>
			</div>
		</div>
		<div class="form-group col-md-4">
			<label class="required"><em>*</em><?= __('End date') ?>:</label>
			<div class="input-box" id="to-container">
				<input type="text" class="required required-entry input-text validate-date form-control"
                       name="to" id="to"
                       value="<?= isset($params['to']) && ($params['to']!="")?$params['to']:""; ?>"
                />
			</div>
		</div>
	</div>
	<script>
		require([
			"jquery",
			"mage/calendar"
			], function($){
				$("#from").calendar({
					buttonText:"<?= __('Select Date') ?>",
				});
				$("#from_date_cal").calendar({
					buttonText:"<?= __('Select Date') ?>",
				});
			});
		require([
			"jquery",
			"mage/calendar"
			], function($){
				$("#to").calendar({
					buttonText:"<?= __('Select Date') ?>",
				});
				$("#to_date_cal").calendar({
					buttonText:"<?= __('Select Date') ?>",
				});
			});
		</script>
		<div class="col-md-12">
			<div class="button-set text-right">
				<button class="button btn btn-warning uptransform"
                        title="<?= __('Export') ?>"
                        onClick="window.location='<?= $this->getUrl('*/*/ExportVproductsCsv',array('_nosid'=>true))?>'"
                        id="export_btn">
					<span>
                        <span>
                            <?= __('Export') ?>
                        </span>
                    </span>
				</button>

				<button class="button btn btn-info uptransform" title="<?= __('Show Report') ?>"
                         id="filter_butn">
					<span>
                        <span>
                            <?= __('Show Report') ?>
                        </span>
                    </span>
				</button>
			</div>
		</div>
	</form>
	<script type="text/javascript">
        require(["jquery"], function ($) {
            $(document).ready(function () {
                $('#filter_butn').click(function () {
                    if ($('#report-form-validate').valid()) {
                         filterVproductsReports(0);
                    }else{
                        return false;
                    }
                });
            });
        });

        function filterVproductsReports(reset){
	        require(["jquery"], function ($) {
                var reportForm = $("#report-form-validate");
                $('#activity-loading').show();
            	var filterUrl = "<?= $this->getUrl('csmarketplace/vreports/filtervproducts/') ?>";
                $.ajax({
                    url: filterUrl,
                    data:{"data":reportForm.serialize()},
                    type:"POST",
                    showLoader: true,
                    success:function(transport){
                        $('#csmarketplace-vreports-vproducts').html(transport);
                        $('#activity-loading').hide();
                    }
                });
        	});
        }

        require(["jquery"], function ($) {
        	$(document).ready(function(){
        		$("#report-form-validate").submit(function() {
        			return false;
        		});
        	});
    		$(window).bind("load", function() {
    			var dataForm = $('#report-form-validate');
    			dataForm.find('input:text').attr('autocomplete', 'off');
    		});
        });
</script>
<style>
	label.required em, span.required em {
		display: none;
	}
	label.required::after, span.required::after {
		color: red;
		content: " *";
		font-family: "Helvetica Neue",Verdana,Arial,sans-serif;
		font-size: 12px;
		font-weight: normal;
	}
</style>
