<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<?php $collection = $this->getVproductsReports();  ?>
<div class="clear"></div>
<form id="payment_form"
action=""
method="post">
    <?= $block->getBlockHtml('formkey'); ?>
<?php if(count($collection)>0){?>
<script type="text/javascript">
	jQuery('#export_btn').show();
	jQuery('#filter_butn6').show();
	jQuery('#filter_butn12').hide();
</script>
<?php }?>
<div class="order-items order-details table-responsive">
	<table id="my-products-table" class="table table-bordered table-hover table-striped">
		<col width="1" />
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<thead>
			<tr>
				<th class="head"><?= __('Product Name') ?></th>
				<th class="head"><?= __('SKU') ?></th> 
				<th class="head"><?= __('Sales Items') ?></th>
				<th class="head"><?= __('Total Sales') ?></th>
				<th class="head"><?= __('Product Type') ?></th>
			</tr>
		</thead>
		<tbody>
			<?php if(count($collection)>0): ?>
				<?php $_odd = ''; ?>
				<?php foreach ($collection as $_report): ?>
					<tr>
						<td class="number"><?= $_report->getOrderItemName();	 ?></td>
						<td class="status"><?= $_report->getSku() ?></td>
						<td class="date"><?= round($_report->getOrderedQty()) ?></td>
						<td class="number"><?= $block->formatCurrency($_report->getOrderItemTotalSales(),false,2,null,$_report->getCurrency()); ?></td>
						<td class="status"><?= $_report->getType_id() ?></td>
					</tr>
				<?php endforeach; ?>
			<?php else: ?>
				<tr><td colspan="5">
					<div>
						<p><?= __('No Report Available'); ?></p>
					</div>
				</td></tr>		
			<?php endif ?>
		</tbody>
	</table>
</div>
</form>
<p class="required"><?= __('* Required Fields') ?></p>
<script type="text/javascript">
	<?php if($this->getRequest()->getActionName()=='vproducts'){ ?>
		require(["jquery"], function ($) {
			filterVproductsReports(2);
		});
		<?php } ?>
		require(["jquery"], function ($) {
			jQuery(document).ready(function(){
				jQuery("#payment_form").submit(function() {
					return false;
				});
			});
		});
	</script>
