<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
      $quoteId = $block->getQuoteId();
      $customer_id = $block->getCustomerId();
      $customer = $block->getCustomer($customer_id);
	  $customer_email = $customer->getEmail();
      $customer_name = $customer->getName();
      $address = $block->getCustomerAddress();
      $quotes = $block->getItems();
      $quoteData = $block->getQuoteData();
?>
<form method="POST" action="<?= /* @noEscape */ $block->getPOUrl();?>">
    <div class="page-main-actions">
        <div class="page-actions-placeholder" style=""></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="#000000021">
                    <div class="page-actions-buttons">
                        <button id="back"
                                title="Back"
                                type="button"
                                class="action-default scalable back"
                                onclick="setLocation('<?= /* @noEscape */ $block->getBackUrl();?>')"
                        >
                            <span><?= /* @noEscape */ __('Back')?></span>
                        </button>
                        <button id="order-view-cancel-button"
                                title="Cancel"
                                type="button"
                                onclick="setLocation('<?= /* @noEscape */ $block->getCancelUrl();?>')"
                        >
                            <span><?= /* @noEscape */ __('Cancel')?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    <section id="order-form_account" class="admin__page-section order-account-information">
        <input  name="quote_id" value="<?= /* @noEscape */ $quoteId;?>" type="hidden">
        <input  name="form_key" value="<?= /* @noEscape */ $block->getFormkey();?>" type="hidden">
    	<div class="admin__page-section-title head-account">
    	    <span class="title"><?= /* @noEscape */ __("Account Information");?></span>
    	    <div class="actions"></div>
    	</div>
    	<div id="customer_account_fieds" class="admin__page-section-content">
            <fieldset class="fieldset admin__fieldset " id="main">

        		<div class="admin__field field field-group_id  required _required" data-ui-id="billing-address-fieldset-element-form-field-group-id">
                    	<label class="label admin__field-label" for="group_id" data-ui-id="billing-address-fieldset-element-select-order-account-group-id-label">	<span><?= /* @noEscape */ __("Customer Group");?></span>
                    	</label>
            			<div class="admin__field-control control">
                			<input id="email"
                                   name=""
                                   data-ui-id="billing-address-fieldset-element-text-order-account-email"
                                   value="<?= /* @noEscape */ $block->getCustomerGroup($customer_id);?>"
                                   class="validate-email admin__control-text input-text admin__control-text"
                                   type="text"
                                   disabled="disabled"
                            />
                        </div>
            	</div>

    		    <div class="admin__field field field-email " data-ui-id="billing-address-fieldset-element-form-field-email" style="width: 35%;">

                    <label class="label admin__field-label" for="email" data-ui-id="billing-address-fieldset-element-text-order-account-email-label"><span><?= /* @noEscape */ __("Customer Email");?></span>
                    </label>
    		        <div class="admin__field-control control">
                        <a href="<?= /* @noEscape */ $block->getUrl('customer/index/edit', ['id' => $customer_id])?>"><?= /* @noEscape */ $customer_email;?></a>
    		        </div>
    		    </div>

                <div class="admin__field field field-email " data-ui-id="billing-address-fieldset-element-form-field-email" style="width: 35%;">

                    <label class="label admin__field-label" for="email" data-ui-id="billing-address-fieldset-element-text-order-account-email-label"><span><?= /* @noEscape */ __("Customer Name");?></span>
                    </label>
                    <div class="admin__field-control control">
                        <a href="<?= /* @noEscape */ $block->getUrl('customer/index/edit', ['id' => $customer_id])?>"><?= /* @noEscape */ $customer_name ?></a>
                    </div>
                </div>
            </fieldset>
        </div>
    </section>

    <section class="admin__page-section order-addresses">

        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __("Address Information");?></span>
        </div>

        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @noEscape */ __("Customer Address Information");?>
                    </span>
                </div>
                <address class="admin__page-section-item-content"><?= /* @noEscape */ $customer_name;?><br>
                        <?= /* @noEscape */ $address['street'];?>
                    <br>
                        <?= /* @noEscape */ $address['city'];?>, <?= /* @noEscape */ $address['state'];?> - <?= /* @noEscape */ $address['pincode'];?>
                    <br>
                        <?= /* @noEscape */ $address['country'];?>
                    <br>
                        T: <?= /* @noEscape */ $address['telephone'];?>
                </address>
            </div>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __('Item(s) Information')?></span>
        </div>
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary edit-order-table" id ="edit-order-table">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @noEscape */__("Product"); ?></span></th>
                        <th class="col-price"><span><?= /* @noEscape */ __("Unit Price"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */ __("Quantity"); ?></span></th>
                        <th class="col-total last"><span><?= /* @noEscape */ __("Row Total"); ?></span></th>
                    </tr>
                </thead>

                <tbody class="even ced-rfq-po-row">
                    <?php
                        $total = 0;
                        foreach ($quotes->getData() as $value) {
                        $product_id = $value['product_id'];
                        $unitprice = $value['unit_price']; ?>
                        <input id="product[<?= /* @noEscape */ $product_id; ?>]"
                               value="<?= /* @noEscape */ $product_id;  ?>"
                               type="hidden"
                        />
                        <tr class="ced-rfq-item-row">
                            <td class="col-product">
                                <div id="order_item_2_title" class="product-title"><?= /* @noEscape */ $value['name'];  ?>
                                </div>
                                <div class="product-sku-block">
                                    <span><?= /* @noEscape */ __("SKU:"); ?></span> <?= /* @noEscape */ $value['sku'];  ?>
                                </div>
                                <?php if ($value['product_type'] == 'configurable' && $customOption = $value['custom_option']){ ?>
                                    <?php $options = json_decode($customOption, true); ?>
                                    <?php if (isset($options['attributes_info']) && is_array($options['attributes_info'])){ ?>
                                        <?php foreach ($options['attributes_info'] as $option): ?>
                                            <div class="product-sku-block">
                                                <span><?= /* @noEscape */ ucfirst($option['label'])?>:</span> <?= /* @noEscape */ $option['value'];  ?>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php }; ?>
                                <?php }; ?>
                            </td>

                            <td class="col-price">
                                <div class="price-excl-tax">
                                    <span><?= /* @noEscape */ $block->getCurrencyCode();  ?></span>
                                    <span class="ced-rfq-price-input">
                                        <?php
                                            $rowUnitPrice = $value['price'];
                                        /* @noEscape */ echo $rowUnitPrice;
                                        ?>
                                    </span>
                                </div>
                            </td>
                            <td class="col-ordered-qty">
                                <div>
                                    <?php
                                    $quoteUpdatedQty = (isset($value['quote_updated_qty']) && $value['quote_updated_qty'] > 0) ?
                                        $value['quote_updated_qty'] : $value['product_qty'];
                                    if ($value['remaining_qty']) {
                                        $max = $value['remaining_qty'];
                                        $poed_qty = $quoteUpdatedQty - $value['remaining_qty'];
                                    } elseif ($value['remaining_qty'] === '0') {
                                        $max = 0;
                                        $poed_qty = $quoteUpdatedQty;
                                    } else {
                                        $max = $quoteUpdatedQty;
                                        $poed_qty = 0;
                                    }
                                    ?>
                                    <input max="<?= /* @noEscape */ $max;?>"
                                           id="quantity_to_po[<?= /* @noEscape */ $product_id; ?>]"
                                           class="input-text admin__control-text qty-input qty-field-po common numbersOnly"
                                           name="item[<?= /* @noEscape */ $value['id'];  ?>]"
                                           value="<?= /* @noEscape */ $max ?>"
                                           type="text"
                                    />
                                </div>
                                <div>
                                    <?= /* @noEscape */ __("Proposal Created for Qty"); ?>:
                                    <b><?= /* @noEscape */ $poed_qty;  ?></b>
                                </div>
                            </td>

                            <td class="col-subtotal">
                                <div class="price-excl-tax">
                                <span><?= /* @noEscape */ $block->getCurrencyCode(); ?></span>
                                    <span class="row-total">
                                        <?= /* @noEscape */ $rowUnitPrice * $max;  ?>
                                    </span>
                                </div>
                            </td>
                        </tr>
                    <?php
                        $total += $rowUnitPrice * $max;
                        }
                    ?>
                </tbody>
            </table>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __("Proposal Total");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-totals">
                <table class="data-table admin__table-secondary order-subtotal-table">
                    <tfoot>
                        <tr class="col-0">
                            <td class="label">
                                <strong><?= /* @noEscape */ __("Grand Total");?></strong>
                            </td>
                            <td>
                                <strong>
                                    <span><?= /* @noEscape */ $block->getCurrencyCode();?></span>
                                    <span id="grandtotalofpo"><?= /* @noEscape */ number_format(($quoteData->getShippingAmount() + $total), 2, '.', '');?></span>
                                </strong>
                            </td>
                        </tr>
                        <tr class="col-3">
                            <td class="label">
                                <strong><?= /* @noEscape */ __("Total Due");?></strong>
                            </td>
                            <td>
                                <strong>
                                    <span><?= /* @noEscape */ $block->getCurrencyCode();?></span>
                                    <span id="totaldue"><?= /* @noEscape */ number_format(($quoteData->getShippingAmount() + $total), 2, '.', '')
                                        ;?></span>
                                </strong>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr class="col-0">
                            <td class="label"><?= /* @noEscape */ __("Subtotal");?></td>
                            <td>
                                <strong>
                                    <span><?= /* @noEscape */ $block->getCurrencyCode();?></span>
                                    <span id="subtotalofpo"><?= /* @noEscape */ number_format($total, 2, '.', '')?></span>
                                </strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="actions">
                    <button title="Submit Order" type="submit" class="action primary" data-ui-id="widget-button-0">
                        <span><?= /* @noEscape */ __("Submit Proposal");?></span>
                    </button>
                </div>
            </div>
        </div>
    </section>
</form>

<script>
    require(['jquery'], function($) {
        $("#edit-order-table").on('keyup', '.qty-field-po',function(){
            var qty = $(this).val();
            var sum = 0;
            var row = $(this).closest('.ced-rfq-item-row');
            var price = parseFloat(row.find('.ced-rfq-price-input').text());
            row.find('.row-total').text(qty*price);
            $("#edit-order-table").find('.ced-rfq-po-row').find('tr').each( function(){
                var qty = $(this).find('.qty-field-po').val();
                var price = parseFloat($(this).find('.ced-rfq-price-input').text());
                sum += parseFloat(qty * price);
            });
            var total = parseFloat(sum);
            $('#subtotalofpo').text(sum.toFixed(2));
            $('#grandtotalofpo').text(total.toFixed(2));
            $('#totaldue').text(total.toFixed(2));
        });

        $(".numbersOnly").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                 // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                 // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                     // let it happen, don't do anything
                     return;
            }
        // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

    });

    require([
    'jquery',
    'jquery/ui',
    'jquery/validate',
    'mage/translate'
    ], function($){
        $('.qty-field-po').keyup(function(){
            if (parseInt($(this).val()) > parseInt($(this).attr('max'))){
                $(this).val($(this).attr('max'));
            }
        });
    });
 </script>
