<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php 
$element = $block->getElement();
$category_ids = [];
?>
<input class="category_ids" name="<?= /* @noEscape */ $element->getName();?>"
       id="<?= /* @noEscape */ $element->getHtmlId()?>"
       type="hidden" value="<?= /* @noEscape */ $block->getIdsString();?>"/>
<div id="<?= /* @noEscape */ $element->getHtmlId()?>_tree" class="tree"></div>

