<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<div class="page-title">
    <h1><?= /* @noEscape */ __('Change Account Password') ?></h1>
</div>
<?= /* @noEscape */ $block->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?= /* @noEscape */ $action ?>" method="post" id="form-validate">

    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>

<div class="fieldset">
    <h2 class="legend"><?= /* @noEscape */ __('Change Account Password') ?></h2>
    <ul class="form-list">
        <li>
            <label for="current_password" class="required"><em>*</em><?= /* @noEscape */ __('Current Password') ?></label>
            <div class="input-box">
                <input type="password" title="<?= /* @noEscape */ __('Current Password') ?>" class="input-text required-entry" name="current_password" id="current_password" />
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password" class="required"><em>*</em><?= /* @noEscape */ __('New Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?= /* @noEscape */ __('New Password') ?>" class="input-text required-entry validate-password" name="password" id="password" />
                </div>
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?= /* @noEscape */ __('Confirm New Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?= /* @noEscape */ __('Confirm New Password') ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set">
    <p class="required"><?= /* @noEscape */ __('* Required Fields') ?></p>
    <p class="back-link"><a href="<?= /* @noEscape */ $block->getUrl('customer/account') ?>"><small>&laquo; </small><?= /* @noEscape */ __('Back') ?></a></p>
    <button type="submit" title="<?= /* @noEscape */ __('Save Password') ?>" class="button"><span><span><?= /* @noEscape */ __('Save Password') ?></span></span></button>
</div>
</form>
