<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */


?>
<?php
$helper = $this->helper(\Ced\CsMarketplace\Helper\Tool\Image::class);
$dataHelper = $this->helper(\Ced\CsMarketplace\Helper\Data::class);
$logo = $helper->getStoreConfig("ced_loginsignup/header/logo", $block->getCurrentStoreId()) ? "ced/csmarketplace/" . $helper->getStoreConfig("ced_loginsignup/header/logo", $block->getCurrentStoreId()) : '';
$logoImage = $helper->getResizeImage($logo, 'logo', 335, 106);
$footerContent = $helper->getStoreConfig("ced_csmarketplace/general/footer_content", $block->getCurrentStoreId());
$isfooterEnable = $helper->getStoreConfig("ced_csmarketplace/general/enable_footer", $block->getCurrentStoreId());
$isadvance = $helper->getStoreConfig("ced_csmarketplace/login_page/design", $block->getCurrentStoreId());
?>

    <div class="ced_vendor_before_login_wrapper">
        <div class="ced_vendor_before_wrap clearfix">
            <div class="ced_vendor_forgot">

                <div class="right">
                    <h3 class="ced_vendor_from_title">
                        <?= /* @noEscape */ __('Forgot Your Password ?') ?>
                    </h3>
                    <div class="panel_body login_form_body">
                        <form class="form password forget"
                              action="<?= /* @noEscape */ $block->getForgotPasswordPostUrl(); ?>"
                              method="post"
                              id="form-validate"
                              data-mage-init='{"validation":{}}'>
                            <fieldset>
                                <p><?= /* @noEscape */ __('Please enter your email address below to receive reset link.') ?></p>
                                <div class="input-box">
                                    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
                                    <input placeholder="<?= /* @noEscape */ __('Email Address') ?>" type="text" name="email"
                                           alt="email" id="email_address"
                                           class="form-control input-text required-entry validate-email"
                                           value="<?= /* @noEscape */ $block->escapeHtml($block->getEmailValue()) ?>"
                                           data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                                <?= /* @noEscape */ $block->getChildHtml('form_additional_info') ?>
                            </fieldset>
                            <div class="buttons-set">
                                <p class="back-link"><a href="<?= /* @noEscape */ $block->getLoginUrl(); ?>">
                                        <small>&laquo;</small><?= /* @noEscape */ __('Back to Login') ?></a></p>
                                <button type="submit" title="<?= /* @noEscape */ __('Reset my password') ?>" class="button">
                                    <span><span><?= /* @noEscape */ __('Reset my password') ?></span></span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php if ($isfooterEnable): ?>
    <?php if ($isadvance) { ?>
        <footer>
            <div class="section_footer">
                <div class="container">
                    <p class="footer_para"><?= /* @noEscape */ $footerContent; ?></p>
                    <ul class="footer_list_right">
                        <?php if ($dataHelper->isFacebookLinkEnabled()) : ?>
                            <li>
                                <a href="<?= /* @noEscape */ $block->getFacebookId() != '' ? 'https://www.facebook.com/' . $block->getFacebookId() : 'JavaScript:void(0);'; ?>"
                                   title="<?= /* @noEscape */ __('Facebook'); ?>">
                                    <i class="fa fa-facebook footer-icon-facebook" aria-hidden="true"></i>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($dataHelper->isTwitterLinkEnabled()) : ?>
                            <li>
                                <a href="<?= /* @noEscape */ $block->getTwitterId() != '' ? 'https://twitter.com/' . $block->getTwitterId() : 'JavaScript:void(0);'; ?>"
                                   title="<?= /* @noEscape */ __('Twitter'); ?>">
                                    <i class="fa fa-twitter footer-icon" aria-hidden="true"></i>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($dataHelper->isLinkedinLinkEnabled()) : ?>
                            <li>
                                <a href="<?= /* @noEscape */ $block->getLinkedinId() != '' ? 'https://in.linkedin.com/' . $block->getLinkedinId() : 'JavaScript:void(0);'; ?>"
                                   title="<?= /* @noEscape */ __('Linkedin'); ?>">
                                    <i class="fa fa-linkedin footer-icon" aria-hidden="true"></i>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($dataHelper->isInstagramLinkEnabled()) : ?>
                            <li>
                                <a href="<?= /* @noEscape */ $block->getInstagramId() != '' ? '//www.instagram.com/' . $block->getInstagramId() : 'JavaScript:void(0);'; ?>"
                                   title="<?= /* @noEscape */ __('Instagram'); ?>">
                                    <i class="fa fa-instagram footer-icon" aria-hidden="true"></i>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </footer>
    <?php } else { ?>
            <div class="ced_vendor_footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="ced_vendor_footer_links">
                                <ul>
                                    <li>
                                        <a href="<?= /* @noEscape */ $block->getBaseUrl(); ?>">
                                            <?= /* @noEscape */ __('Home') ?>
                                        </a>
                                        |
                                    </li>
                                    <li>
                                        <a href="<?= /* @noEscape */ $block->getBaseUrl() . 'contact'; ?>">
                                            <?= /* @noEscape */ __('Contact') ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <p><?= /* @noEscape */ $footerContent; ?></p>
                        </div>
                    </div>
                </div>
            </div>
    <?php } ?>
<?php endif; ?>
