<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$helper = $this->helper(\Ced\CsMarketplace\Helper\Tool\Image::class);
$enable_tc = $helper->getStoreConfig("ced_csmarketplace/general/enable_tc",$block->getCurrentStoreId());
$tc_content = $helper->getStoreConfig("ced_csmarketplace/general/tc_content",$block->getCurrentStoreId());
$helper_data = $this->helper('Ced\CsMarketplace\Helper\Data');
$vendor_attribute_enable = $helper_data->getStoreConfig('ced_csvendorattribute/general/activation');
?>

<form class="form create account form-create-account" action="<?= /* @noEscape */ $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" onsubmit ="return validateshopurl()" autocomplete="off" role="form">
    <fieldset>
        <div class="panel panel-default">
            <input type="hidden" name="success_url" value="<?= /* @noEscape */ $block->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?= /* @noEscape */ $block->getErrorUrl() ?>" />
            <div class="panel-heading"><?= /* @noEscape */ __('Personal Information') ?></div>
            <div class="panel-body">
                <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->setTemplate('Ced_CsMarketplace::customer/widget/name.phtml')->toHtml() ?>
                <div class="input-box email">
                    <input placeholder="<?= /* @noEscape */ __('Email Address') ?>" type="text" name="email" id="email_address" value="<?= $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?= /* @noEscape */ __('Email Address') ?>" class="form-control input-text validate-email required-entry" data-validate="{required:true, 'validate-email':true}" />
                </div>
                <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                <?php endif ?>
                <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                <?php endif ?>
                <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                <?php endif ?>
            </div>
        </div>
    </fieldset>
    <?= $block->getChildHtml('vendor_reg_form') ?>
    <?php if($block->getShowAddressFields()): ?>
        <fieldset>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <input type="hidden" name="create_address" value="1" />
                    <?= /* @noEscape */ __('Address Information') ?>
                </div>
                <div class="panel-body">
                    <ul class="form-list nav">
                        <li class="fields">
                            <div class="field">
                                <div class="input-box">
                                    <input placeholder="<?= /* @noEscape */ __('Company') ?>" type="text" name="company" id="company" value="<?= $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?= /* @noEscape */ __('Company') ?>" class="form-control input-text <?= /* @noEscape */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>" />
                                </div>
                            </div>
                            <div class="field">
                                <div class="input-box">
                                    <input placeholder="<?= /* @noEscape */ __('Telephone') ?>" type="text" name="telephone" id="telephone" value="<?= $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?= /* @noEscape */ __('Telephone') ?>" class="form-control input-text required-entry <?= /* @noEscape */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" />
                                </div>
                            </div>
                        </li>
                        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
                        <li class="wide">
                            <div class="input-box">
                                <input placeholder="<?= /* @noEscape */ __('Street Address') ?>" type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreet(1)) ?>" title="<?= /* @noEscape */ __('Street Address') ?>" id="street_1" class="form-control input-text required-entry <?= /* @noEscape */ $_streetValidationClass ?>" />
                            </div>
                        </li>
                        <?php for ($_i=2, $_n=$this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                            <li class="wide">
                                <div class="input-box">
                                    <input placeholder="<?= /* @noEscape */ __('Street Address') ?>" type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreet($_i)) ?>" title="<?= /* @noEscape */ __('Street Address %s', $_i) ?>" id="street_<?= /* @noEscape */ $_i?>" class="form-control input-text <?= /* @noEscape */ $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php endfor ?>
                        <li class="fields">
                            <div class="field">
                                <div class="input-box">
                                    <input placeholder="<?= /* @noEscape */ __('City') ?>" type="text" name="city" value="<?= $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ __('City') ?>" class="form-control input-text required-entry <?= /* @noEscape */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city" />
                                </div>
                            </div>
                            <div class="field">
                                <div class="input-box">
                                    <select placeholder="<?= /* @noEscape */ __('State/Province') ?>" id="region_id" name="region_id" title="<?= /* @noEscape */ __('State/Province') ?>" class="validate-select <?= /* @noEscape */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                                        <option value=""><?= /* @noEscape */ __('Please select region, state or province') ?></option>
                                    </select>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <div class="input-box">
                                    <input placeholder="<?= /* @noEscape */ __('Zip/Postal Code') ?>" type="text" name="postcode" value="<?= $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ __('Zip/Postal Code') ?>" id="zip" class="form-control input-text validate-zip-international required-entry <?= /* @noEscape */ $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="country" class="required"><em>*</em><?= /* @noEscape */ __('Country') ?></label>
                                <div class="input-box">
                                    <?= $block->getCountryHtmlSelect() ?>
                                </div>
                            </div>
                        </li>
                    </ul>

                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <ul>
                            <li>
                                <?php $addressAttributes->setEntityType('customer_address'); ?>
                                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                                <?= $addressAttributes->setShowContainer(false)->toHtml()?>
                            </li>
                        </ul>
                    <?php endif;?>

                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
                </div>
            </div>
        </fieldset>
    <?php endif; ?>
    <fieldset>
        <div class="panel panel-default">
            <div class="panel-heading"><?= /* @noEscape */ __('Login Information') ?></div>
            <div class="panel-body">
                <div class="field password enter-password required">
                    <div class="input-box">
                        <input placeholder="<?= /* @noEscape */ __('Password') ?>" type="password" name="password" id="password"
                               title="<?= /* @noEscape */ __('Password') ?>"
                               class="form-control input-text"
                               data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                               data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                               data-validate="{required:true, 'validate-customer-password':true}"
                               autocomplete="off">

                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field confirmation enter-confirm-password">
                    <div class="input-box">
                        <input placeholder="<?= /* @noEscape */ __('Confirm Password') ?>" type="password" name="password_confirmation" title="<?= /* @noEscape */ __('Confirm Password') ?>" id="password-confirmation" class="form-control input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="clearfix">
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="checkbox">
                <input type="checkbox" name="is_subscribed" title="<?= /* @noEscape */ __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                <label for="is_subscribed">
                    <?= /* @noEscape */ __('Sign Up for Newsletter') ?>
                </label>
            </div>
        <?php endif ?>
    </div>
    <!-- For Terms & conditions  -->
    <?php if($enable_tc){ ?>
        <div class="clearfix">
            <div class="checkbox">
                <input name="terms" title="Terms and Condition" id="terms" class="checkbox required" type="checkbox">
                <label for="terms">
                    <?= /* @noEscape */ __("I've read and accept ") ?>
                    <a class="term_condition" href="javascript:void(0)"><?= /* @noEscape */ __("terms and condition") ?></a>
                </label>
            </div>
        </div>

    <?php } ?>
    <div class="panel-body">
        <?= $block->getChildHtml('form_additional_info') ?>
    </div>
    <div class="content">
        <div class="buttons-set">
            <button type="submit" id ="submit_button_id" title="<?= /* @noEscape */ __('Submit') ?>" class="button" disabled="disabled"><span><span><?= /* @noEscape */ __('Submit') ?></span></span></button>
        </div>
    </div>
    <div class="vendor_exitance">
        <?= /* @noEscape */ __('Already have a vendor account? ') ?>
        <a href="#" class="axisting_venor"><?= /* @noEscape */ __('Sign in') ?></a>
    </div>
</form>
<div class="search_form_overlay ced-modal-overlay" style="display:none">
    <div class="terms-condition ced-modal-content">
        <div class="terms-header ced-modal-header">
            <h3><?= /* @noEscape */ __('Terms And Condition')?></h3>
            <span title="Close" class="close_term ced_close">X</span>
        </div>
        <div class="terms-inner ced-modal-data">
            <?=
            $this->getLayout()
                ->createBlock(\Magento\Cms\Block\Block::class)
                ->setBlockId($tc_content)
                ->toHtml();
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function(jQuery){
        jQuery(window).load(function(){
            var formDataCount = "<?= $block->escapeHtml($block->getRequest()->getParam('create')) ?>";
            if (parseInt(formDataCount) == 1) {
                jQuery('.new_venor').trigger('click');
            }
        });
    });
</script>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        $(document).ready(function() {
            $('#submit_button_id').prop('disabled', false);
        });
        var dataForm = $('#form-validate');
        $('#submit_button_id').on('click', function () {
            if(dataForm.valid()) {
                $('#submit_button_id').prop('disabled', true);
                dataForm.submit();
            }
        });
        var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        $("#prefix").siblings().remove();
        $("#suffix").addClass( "form-control" );
        <?php if ($_gender->isEnabled()): ?>
        $(".gender").addClass( "input-box" );
        $("#gender").addClass( "form-control" );
        $(".gender > label:first").remove();
        $("#gender").find("option").eq(0).remove();
        $("#gender").prepend('<option value="" selected>Select Gender</option>');
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
        $(".taxvat").addClass( "input-box" );
        $(".taxvat > label:first").remove();
        $("#taxvat").attr("placeholder", "Taxvat");
        var taxvatHtml = $('#taxvat').clone();
        $('#taxvat').parent().remove();
        $(".taxvat").append(taxvatHtml).html();
        <?php endif ?>
        <?php if ($_dob->isEnabled()){ ?>

        $(".field-dob").addClass( "input-box" );
        $("#dob").addClass( "form-control" );
        $("#dob").attr("placeholder", "Date Of Birth");

        <?php }?>
        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    });
</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
			{
			"#country": {
			"regionUpdater": {
			"optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
			"regionListId": "#region_id",
			"regionInputId": "#region",
			"postcodeId": "#zip",
			"form": "#form-validate",
			"regionJson": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
			"defaultRegion": "<?= /* @noEscape */ $block->getFormData()->getRegionId() ?>",
			"countriesWithOptionalZip": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
		}
	}
}
</script>
<?php endif; ?>
<?php if($vendor_attribute_enable){?>
    <script type="text/x-magento-init">
		{
			"#ced-country-id-field": {
				"regionUpdater": {
					"optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
					"regionListId": "#ced-region-id-field",
					"regionInputId": "#ced-region-field",
					"postcodeId": "#ced-zip-code-field",
					"form": "#form-validate",
					"regionJson": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
					"defaultRegion": "<?= /* @noEscape */ $block->getFormData()->getRegionId() ?>",
					"countriesWithOptionalZip": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
				}
			}
		}
	</script>
<?php }?>
<script>
    function validateshopurl()
    {
        var patt = /^([a-zA-Z0-9\-])+$/;
        var shopurl = document.getElementById('ced-shop-url-field').value;
        if (patt.test(shopurl)) {
            document.getElementById("advice-validate-shopurl-ced-shop-url-field").style.display = 'none';
            return true;
        } else {
            document.getElementById('advice-validate-shopurl-ced-shop-url-field').innerHTML="Invalid Shop Url";
            document.getElementById("advice-validate-shopurl-ced-shop-url-field").style.display = 'block';
            return false;
        }
    }
</script>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        $('.term_condition').click(function(){
            $('.ced-modal-overlay').fadeIn('300');
            $('.csmarketplace-account-login').addClass('modal-active');
        });
        $('.ced_close').click(function(){
            $('.ced-modal-overlay').fadeOut('300');
            $('.csmarketplace-account-login').removeClass('modal-active');
        });
    });
</script>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
