<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$_order = $block->getOrder();
$vorder = $block->getVOrder();
?>
<?php
if ($block->getRequest()->getActionName() != "print") {
    ?>
    <div class="buttons-set col-md-6  col-xs-12 buttons_scb">
        <button type="button" onclick="window.open('<?= /* @noEscape */ $block->getPrintUrl($vorder); ?>')"
                title="<?= /* @noEscape */ __('Print Order') ?>"
                class="button btn btn-warning uptransform pull-right">
            <span>
                <span><?= /* @noEscape */ __('Print Order') ?></span>
            </span>
        </button>
    </div>
<?php } ?>
<?= /* @noEscape */ $block->getChildHtml(); ?>
