<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<?php  $products = $block->getProducts(); ?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;" summary="<?= /* @noEscape */ __('Products') ?>">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?= /* @noEscape */ __('Product Name') ?></th>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?= /* @noEscape */ __('SKU') ?></th>
        </tr>
    </thead>
    <tbody  bgcolor="#F6F6F6">
    <?php $i=0;?>
    <?php if(!empty($products[0])):?>
        <?php foreach ($products[0] as $product): ?>
            <tr align="left" 
                style="font-size: 13px; padding: 3px 9px" <?= $i%2 ? ' bgcolor="#EAEAEA"' : '#F6F6F6' ?> class="border">
                <td class="number">
                <?php if($products[1][$product->getId()]->getCheckStatus()==\Ced\CsMarketplace\Model\Vproducts::APPROVED_STATUS && $product->getStatus()==\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED){?>
                <a href="<?= /* @noEscape */ $product->getProductUrl() ?>" title="<?= /* @noEscape */ $product->getName()?>" ><?= /* @noEscape */ $product->getName();?></a>
                <?php }else{?>
                <?= /* @noEscape */ $product->getName();?>
                <?php if($products[1][$product->getId()]->getReason()){
                	?><div><?= /* @noEscape */ "Disapproval Reason : " . $products[1][$product->getId()]->getReason(); ?></div><?php
                }?>
                <?php }?>
                </td>
                <td class="number"><?= /* @noEscape */ $product->getSku();?></td>
            </tr>
            <?php $i++;?>
        <?php endforeach; ?>
    <?php endif;?>
    </tbody>
</table>
