<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsProduct
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
/* @var Magento\ProductVideo\Block\Adminhtml\Product\Edit\NewVideo $block */
?>
<div id="<?= /* @noEscape */
$block->getNameInLayout(); ?>" style="display:none"
     data-modal-info='<?= $block->escapeHtmlAttr($block->getWidgetOptions()); ?>'>
    <?= $block->escapeHtmlAttr($block->getFormHtml()); ?>
    <div id="video-player-preview-location" class="video-player-sidebar">
        <div class="video-player-container"></div>
        <div class="video-information title">
            <label><?= $block->escapeHtml(__('Title:')) ?> </label><span></span>
        </div>
        <div class="video-information uploaded">
            <label><?= $block->escapeHtml(__('Uploaded:')) ?> </label><span></span>
        </div>
        <div class="video-information uploader">
            <label><?= $block->escapeHtml(__('Uploader:')) ?> </label><span></span>
        </div>
        <div class="video-information duration">
            <label><?= $block->escapeHtml(__('Duration:')) ?> </label><span></span>
        </div>
    </div>
</div>
