<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<div data-bind="scope: 'messages'" id="msg-popup-wrapper">
<!-- ko if: cookieMessages && cookieMessages.length > 0 -->
     <div class="modal fade" id="error-msg-modal" role="dialog">
        <div class="modal-dialog modal-wrap" data-bind="foreach: { data: cookieMessages, as: 'message' }">

            <div class="modal-content model-container" data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
                <div class="modal-header modal-head-content">
                    <h4 class="modal-title">
                        <!-- ko if: message.type == 'error'  -->
                            <i class="fa fa-exclamation-triangle icon-error" aria-hidden="true"></i>
                        <!-- /ko -->
                    </h4>
                </div>
                <div class="modal-body modal-body-content">
                    <!-- ko if: message.type == 'error'  -->
                        <p><strong><?= /* @noEscape */ __('OOPS'); ?>!</strong></p>
                    <!-- /ko -->
                    <p data-bind="html: message.text"></p>
                </div>
                <div class="modal-footer modal-footer-content">
                    <a href="#" id="close-msg-pop" data-dismiss="modal" data-target="#error-msg-modal"><?= /* @noEscape */ __('Cancel'); ?></a>
                </div>
            </div>

        </div>
    </div>
    <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Ced_CsMarketplace/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
