<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile
?>
<?php 
$helper = $this->helper('Ced\CsMarketplace\Helper\Tool\Image');
$logo = $helper->getStoreConfig("ced_loginsignup/header/logo", $block->getCurrentStoreId()) ? "ced/csmarketplace/".$helper->getStoreConfig("ced_loginsignup/header/logo",$block->getCurrentStoreId()) : '';
$logoImage = $helper->getResizeImage($logo, 'logo', 335, 106); 
$footerContent = $helper->getStoreConfig("ced_csmarketplace/general/footer_content",$block->getCurrentStoreId());
$isfooterEnable = $helper->getStoreConfig("ced_csmarketplace/general/enable_footer",$block->getCurrentStoreId());
?>
<div class="ced_vendor_header">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-left">
          <div class="v_header_logo">
            <?php if($logo):?>
              <a href="<?= $block->getBaseUrl(); ?>" target="_blank">
                <img src="<?= $logoImage ?>" alt="vendor panel logo">
              </a>
            <?php else:?>
              <a href="<?= $block->getBaseUrl(); ?>" target="_blank">
              <img src="<?= $block->getViewFileUrl('images/demo.png'); ?>" alt="vendor panel logo">
              </a>
            <?php endif;?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="ced_vendor_before_login_wrapper">
  <div class="ced_vendor_before_wrap clearfix">
    <div class="ced_vendor_forgot">
      <div class="right">
        <h3 class="ced_vendor_from_title">
          <?= __('Reset My Password') ?>
        </h3>
        <div class="panel_body login_form_body">
<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]])) ?>"
      method="post"
      <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password forget"
      data-mage-init='{"validation":{}}'>
    <fieldset data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <div class="input-box">
               <input placeholder="<?= __('New Password') ?>" type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation required">
            <div class="input-box">
                <input placeholder="<?= __('Confirm New Password') ?>" type="password" class="form-control input-text required-entry" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="buttons-set">
            <button type="submit" title="<?= __('Reset My Password') ?>" class="button"><span><span><?= __('Reset My Password') ?></span></span></button>
    </div>
</form>
</div>
    </div>
  </div>
</div>
</div>
<?php if($isfooterEnable): ?>
<div class="ced_vendor_footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="ced_vendor_footer_links">
          <ul>
            <li>
              <a href="<?= $block->getBaseUrl(); ?>">
                <?= __('Home') ?>
              </a>
              |
            </li>
            <li>
              <a href="<?= $block->getBaseUrl().'contact'; ?>">
                <?= __('Contact') ?>
              </a>
              |
            </li>
          </ul>
        </div>
          <p><?= $footerContent; ?></p>
      </div>
    </div>
  </div>
</div>
<?php endif;?>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-password-forget"
            }
        }
    }
</script>