<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsProduct
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https//cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Backend\Block\Widget\Button\SplitButton */
?>
<div <?= $block->getAttributesHtml(); ?>>
    <button <?= $block->getButtonAttributesHtml(); ?>>
        <span><?= $block->escapeHtml($block->getLabel()); ?></span>
    </button>
    <?php if ($block->hasSplit()): ?>
        <button <?= $block->getToggleAttributesHtml() ?>>
            <span>Select</span>
        </button>

        <?php if (!$block->getDisabled()): ?>
            <ul class="dropdown-menu" <?= /* @noEscape */ $block->getUiId("dropdown-menu"); ?>>
                <?php foreach ($block->getOptions() as $key => $option): ?>
                    <li>
                    <span <?= $block->getOptionAttributesHtml($key, $option); ?>>
                        <?= $block->escapeHtml($option['label']); ?>
                    </span>
                        <?php if (isset($option['hint'])): ?>
                            <div class="tooltip" <?= /* @noEscape */ $block->getUiId('item', $key, 'tooltip'); ?>>
                                <a href="<?= $block->escapeHtml($option['hint']['href']) ?>" class="help">
                                    <?= $block->escapeHtml($option['hint']['label']) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>

<script>
    require(['jquery'], function ($) {
        $('.actions-split')
            .on('click.splitDefault', '.action-default', function () {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
    });
</script>

<!--<select onchange="javascript:location.href = this.value;">
	<option value="http://192.168.0.25/Mage2/csproduct/vproducts/new/set/4/type/simple/">Add Product </option>
	<?php foreach ($block->getOptions() as $key => $option) { ?>
			<option value="<?= /* @noEscape */ $option['href'] ?>">
				<?php echo $block->escapeHtml($option['label']); ?>
			</option>
	<?php } ?>
</select>-->
