<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
$vorder = $this->helper('Ced\CsMarketplace\Helper\Data')->getCurrentVorder();
$_order  = $block->getOrder();
$_source = $block->getSource();
$_fullInfo  = $block->getFullTaxInfo();
?>
<?php if($vorder->getBaseTaxAmount()){?>
<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        <?php if ($block->helper('tax')->displayFullSummary()): ?>
            <?= __('Total Tax') ?>
        <?php else: ?>
            <?= __('Tax') ?>
        <?php endif;?>
        </div>
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <?= $block->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php }?>
</tr>
