<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsVendorReview
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 */
$_items = $block->getReviews();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$_votes = $block->getRatings();
$isAllowed = $block->isAllowed();
$checkVendorProducts = $block->checkVendorProducts();
$messages = $block->getMessages();
if ($msg = $messages->getLastAddedMessage()) { ?>
    <script>
        require(['mage/url','jquery'], function() {
            jQuery('.messages')
                .first()
                .after('<div class="message-success success message">' +
                    '<div><?= $escaper->escapeHtml($msg->getText())?></div></div>');
        });
    </script>
<?php } ?>

<div class="block review-list" id="customer-reviews">
    <div class="block-title">
    </div>
    <?php
    if ($isAllowed) {
        if (!$checkVendorProducts) {
            if (!$block->isUserLoggedIn()) { ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= $escaper->escapeHtml(__('Please login to review product!')) ?>
                    </div>
                </div>
            <?php } else { ?>

                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= $escaper->escapeHtml(
                            __('You cannot review this vendor as you have not purchased any item from this vendor.')
                        )?>
                    </div>
                </div>
            <?php } ?>
        <?php } else {
            echo $block->getChildHtml('csvendorreview_rating_form');
        }
    } else { ?>
        <?= $block->getChildHtml('csvendorreview_rating_form'); ?>
    <?php } ?>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
            <?php foreach ($_items as $_review):?>
                <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                    <?php if (count($_votes)): ?>
                        <div class="review-ratings">
                            <?php foreach ($_votes as $_vote): ?>
                                <?php if ($_review[$_vote->getRatingCode()]!=''): ?>
                                    <div class="rating-summary item" itemprop="reviewRating"
                                         itemscope itemtype="http://schema.org/Rating">
                                        <span class="label rating-label">
                                            <span><?= $escaper->escapeHtml($_vote->getRatingLabel()) ?></span>
                                        </span>
                                        <div class="rating-result"
                                             title="<?= $escaper->escapeHtml($_review[$_vote->getRatingCode()]) ?>%">
                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width:
                                            <?= $escaper->escapeHtml($_review[$_vote->getRatingCode()]) ?>%;">
                                                <span>
                                                    <?= $escaper->escapeHtml($_review[$_vote->getRatingCode()])?>%
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                <?php endif;?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div itemprop="subject" class="review-content">
                        <strong><?= $escaper->escapeHtml(nl2br($_review->getSubject())); ?></strong>
                    </div>
                    <div class="review-content" itemprop="description">
                        <?= $escaper->escapeHtml(nl2br($_review->getReview())); ?>
                    </div>
                    <div class="review-details">
                        <p class="review-author">
                            <span class="review-details-label"><?= $escaper->escapeHtml(__('By'))?></span>
                            <strong class="review-details-value" itemprop="author">
                                <?= $escaper->escapeHtml($_review->getCustomerName()); ?>
                            </strong>
                        </p>
                        <p class="review-date">
                            <span class="review-details-label"><?= $escaper->escapeHtml(__('Posted on')) ?></span>
                            <time class="review-details-value" itemprop="datePublished" datetime="
                            <?php $block->formatDate($_review->getCreatedAt(), $format)  ?>">
                                <?= $escaper->escapeHtml(
                                    __(' on ') . $block->formatDate($_review->getCreatedAt(), $format)
                                )?>
                            </time>
                        </p>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
