<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php

/** @var Ced\CsMarketplace\Block\Vshops\View  $block*/

$helper = $block->imageHelper();
$width = (int)$helper->getStoreConfig('ced_vshops/general/logo_image_width', $block->getCurrentStoreId());
$height = (int)$helper->getStoreConfig('ced_vshops/general/logo_image_height', $block->getCurrentStoreId());
$width = $width ? $width : 175;
$height = $height ? $height : 150;
$mediaUrl = $block->getMediaUrl();

?>
<?php if ($block->aclHelper()->isEnabled()) { ?>
    <div class="block block-poll">
        <div class="block-content">
            <img src="<?= /* @noEscape */ $helper->getResizeImage($block->getVendorLogo(), 'logo', $width, $height); ?>" />
            <ul>
                <?php foreach ($block->getLeftProfileAttributes() as $attribute) { ?>
                    <?php $attribute->setStoreId($block->getStoreId()); ?>
                    <?php if ($block->escapeHtml($block->Method($attribute->getAttributeCode())) != '') { ?>
                        <li>
                            <?php if ($attribute->getFrontendInput() == 'file' || $attribute->getFrontendInput() == 'image') : ?>
                                <label>
                                    <i class="<?= /* @noEscape */ $attribute->getData('fontawesome_class_for_left_profile'); ?>"></i>
                                    <?php if (strlen($attribute->getStoreLabel()) > 0) {
                                        /* @noEscape */
                                        echo __($attribute->getStoreLabel());
                                    } else {
                                        /* @noEscape */
                                        echo __($attribute->getFrontendLabel());
                                    } ?> :</label> <a target="_blank" href="<?= /* @noEscape */ $mediaUrl . $block->escapeHtml($block->Method($attribute->getAttributeCode())) ?>"><?= /* @noEscape */ (__($block->baseName($block->escapeHtml($block->Method($attribute->getAttributeCode()))))); ?></a>
                            <?php else : ?>
                                <label>
                                    <i class="<?= /* @noEscape */ $attribute->getData('fontawesome_class_for_left_profile'); ?>"></i>
                                    <?php if (!empty($attribute->getStoreLabel())) {
                                        /* @noEscape */
                                        echo __($attribute->getStoreLabel());
                                    } else {
                                        /* @noEscape */
                                        echo __($attribute->getFrontendLabel());
                                    } ?> :</label><span> <?php if ($attribute->usesSource()) {
                                                                $data = $block->getCountryname($block->Method($attribute->getAttributeCode()));
                                                                if (is_array($data)) {
                                                                    $data = implode(', ', $data);
                                                                }
                                                                /* @noEscape */
                                                                echo $data;
                                                            } else if ($attribute->getFrontendInput() == 'date') {
                                                                /* @noEscape */
                                                                echo $block->getTimezone($block->Method($attribute->getAttributeCode()));
                                                            } else {
                                                                if ($attribute->getData('fontawesome_class_for_left_profile') == 'fa fa-facebook-square') { ?>
                                            <a href="https://www.facebook.com/<?= /* @noEscape */  $block->escapeHtml($block->Method($attribute->getAttributeCode())); ?>"><?= /* @noEscape */ $block->escapeHtml($block->Method($attribute->getAttributeCode())); ?></a>
                                        <?php } elseif ($attribute->getData('fontawesome_class_for_left_profile') == 'fa fa-twitter') { ?>
                                            <a href="https://twitter.com/<?= /* @noEscape */$block->escapeHtml($block->Method($attribute->getAttributeCode())); ?>"><?= /* @noEscape */ $block->escapeHtml($block->Method($attribute->getAttributeCode())); ?></a>
                                    <?php } else {
                                                                    /* @noEscape */
                                                                    if ($attribute->getData('fontawesome_class_for_left_profile') == 'fa fa-calendar') {
                                                                        $vcreatedat = $block->escapeHtml($block->Method($attribute->getAttributeCode()));
                                                                        $newtimestamp = strtotime($vcreatedat . '-6 hour -30 minutes');
                                                                        echo $add_date = date('Y-m-d H:i:s', strtotime($vcreatedat . '-6 hour -30 minutes'));
                                                                    } else {
                                                                        echo __($block->escapeHtml($block->Method($attribute->getAttributeCode())));
                                                                    }
                                                                }
                                                            } ?>
                                </span>
                            <?php endif; ?>
                        </li>
                <?php }
                }
                ?>
            </ul>
        </div>
    </div>

<?php } ?>