<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr<?php if (!$block->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
    <td>
        <?php if ($block->canDisplayContainer()): ?>
        <div id="<?= /* @noEscape */ $block->getHtmlId() ?>"
             class="item-container">
            <?php endif; ?>
            <div class="item-text">
                <?= /* @noEscape */ $block->getColumnHtml($_item, 'name') ?>
            </div>
            <?php if ($block->canDisplayContainer()): ?>
        </div>
    <?php endif ?>
    </td>
    <td class="a-right"><?= /* @noEscape */ $block->getColumnHtml($_item, 'status') ?></td>
    <td class="a-right"><?= /* @noEscape */ $block->displayPriceAttribute('original_price') ?></td>
    <td class="a-right">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices() ||
            $this->helper('Magento\Tax\Helper\Data')->displaySalesPriceExclTax()
        ): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices()): ?>
                    <span class="label"><?= /* @noEscape */ __('Excl. Tax'); ?>:</span>
                <?php endif; ?>

                <?php if ($this->helper('Magento\Weee\Helper\Data')->typeOfDisplay(array(0, 1, 4), 'sales',
                    $_item->getStoreId())
                ): ?>
                    <?php
                    echo $this->displayPrices(
                        $_item->getBasePrice() + $_item->getBaseWeeeTaxAppliedAmount() +
                        $_item->getBaseWeeeTaxDisposition(),
                        $_item->getPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?= /* @noEscape */ $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
                <?php endif; ?>


                <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                    <br/>
                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?= /* @noEscape */ $tax['title']; ?>
                                    : <?= /* @noEscape */ $this->displayPrices($tax['base_amount_incl_tax'],
                                        $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_amount_incl_tax'],
                                    $tax['amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <br/>
                        <span class="nobr"><?= /* @noEscape */ $this->helper('Magento\Weee\Helper\Data')->__('Total'); ?>:<br/>
                            <?php
                            echo $this->displayPrices(
                                $_item->getBasePrice() + $_item->getBaseWeeeTaxAppliedAmount() +
                                $_item->getBaseWeeeTaxDisposition(),
                                $_item->getPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()
                            );
                            ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices() ||
            $this->helper('Magento\Tax\Helper\Data')->displaySalesPriceInclTax()
        ): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices()): ?>
                    <span class="label"><?= /* @noEscape */ __('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('Magento\Checkout\Helper\Data')->getPriceInclTax($_item); ?>
                <?php $_baseIncl = $this->helper('Magento\Checkout\Helper\Data')->getBasePriceInclTax($_item); ?>

                <?php if ($this->helper('Magento\Weee\Helper\Data')
                    ->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())
                ): ?>
                    <?= /* @noEscape */ $this->displayPrices($_baseIncl + $_item->getBaseWeeeTaxAppliedAmount(),
                        $_incl + $_item->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?= /* @noEscape */ $this->displayPrices($_baseIncl - $_item->getBaseWeeeTaxDisposition(),
                        $_incl - $_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

                <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                    <br/>
                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?= /* @noEscape */ $tax['title']; ?>
                                    : <?= /* @noEscape */ $this->displayPrices($tax['base_amount_incl_tax'],
                                        $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_amount_incl_tax'],
                                    $tax['amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <br/>
                        <span class="nobr"><?= /* @noEscape */ $this->helper('Magento\Weee\Helper\Data')->__('Total'); ?>
                            :<br/> <?= /* @noEscape */ $this->displayPrices($_baseIncl + $_item->getBaseWeeeTaxAppliedAmount(),
                                $_incl + $_item->getWeeeTaxAppliedAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>

    </td>
    <td><?= /* @noEscape */ $this->getColumnHtml($_item, 'qty') ?></td>

    <td class="a-right">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices() ||
            $this->helper('Magento\Tax\Helper\Data')->displaySalesPriceExclTax()
        ): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices()): ?>
                    <span class="label"><?= /* @noEscape */ __('Excl. Tax'); ?>:</span>
                <?php endif; ?>

                <?php if ($this->helper('Magento\Weee\Helper\Data')->typeOfDisplay(array(0, 1, 4), 'sales',
                    $_item->getStoreId())
                ): ?>
                    <?php
                    echo $this->displayPrices(
                        $_item->getBaseRowTotal() + $_item->getBaseWeeeTaxAppliedRowAmount() +
                        $_item->getBaseWeeeTaxRowDisposition(),
                        $_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() +
                        $_item->getWeeeTaxRowDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?= /* @noEscape */ $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
                <?php endif; ?>


                <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount'],
                                    $tax['row_amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?= /* @noEscape */ $tax['title']; ?>
                                    : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount_incl_tax'],
                                        $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount_incl_tax'],
                                    $tax['row_amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <br/>
                        <span class="nobr"><?= /* @noEscape */ $this->helper('Magento\Weee\Helper\Data')->__('Total'); ?>:<br/>
                            <?php
                            echo $this->displayPrices(
                                $_item->getBaseRowTotal() + $_item->getBaseWeeeTaxAppliedRowAmount() +
                                $_item->getBaseWeeeTaxRowDisposition(),
                                $_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() +
                                $_item->getWeeeTaxRowDisposition()
                            );
                            ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices() ||
            $this->helper('Magento\Tax\Helper\Data')->displaySalesPriceInclTax()
        ): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices()): ?>
                    <span class="label"><?= /* @noEscape */ __('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('Magento\Checkout\Helper\Data')->getSubtotalInclTax($_item); ?>
                <?php $_baseIncl = $this->helper('Magento\Checkout\Helper\Data')->getBaseSubtotalInclTax($_item); ?>
                <?php if ($this->helper('Magento\Weee\Helper\Data')
                    ->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())
                ): ?>
                    <?= /* @noEscape */ $this->displayPrices($_baseIncl + $_item->getBaseWeeeTaxAppliedRowAmount(),
                        $_incl + $_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?= /* @noEscape */ $this->displayPrices($_baseIncl - $_item->getBaseWeeeTaxRowDisposition(),
                        $_incl - $_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>


                <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>

                    <br/>
                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount'],
                                    $tax['row_amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?= /* @noEscape */ $tax['title']; ?>
                                    : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount_incl_tax'],
                                        $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())
                    ): ?>
                        <small>
                        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?= /* @noEscape */ $tax['title']; ?>
                                : <?= /* @noEscape */ $this->displayPrices($tax['base_row_amount_incl_tax'],
                                    $tax['row_amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if ($this->helper('Magento\Weee\Helper\Data')
                        ->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())
                    ): ?>
                        <br/><span class="nobr"><?= /* @noEscape */ $this->helper('Magento\Weee\Helper\Data')->__('Total'); ?>
                            :<br/> <?= /* @noEscape */ $this->displayPrices($_baseIncl +
                                $_item->getBaseWeeeTaxAppliedRowAmount(),
                                $_incl + $_item->getWeeeTaxAppliedRowAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </td>
    <td class="a-right"><?= /* @noEscape */ $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?= /* @noEscape */ number_format($_item->getData()['tax_percent'],2). '%' ?></td>
    <td class="a-right"><?= /* @noEscape */ $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right last">
        <?= /* @noEscape */ $this->displayPrices(
            $_item->getBaseRowTotal() - $_item->getBaseDiscountAmount() + $_item->getBaseTaxAmount() +
            $_item->getBaseWeeeTaxAppliedRowAmount(),
            $_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount() +
            $_item->getWeeeTaxAppliedRowAmount()
        ); ?>
    </td>
</tr>
