<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<?php $_element = $this->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?= $_element->getFieldsetContainerId(); ?>">
<?php endif; ?>
<div class="fieldset">
<?php if ($_element->getLegend()): ?>
    <h2 class="legend"><?= $_element->getLegend() ?></h2>
<?php endif; ?>
<?php if (!$_element->getNoContainer()): ?>
    <ul class="form-list <?= $_element->getClass() ?>" id="<?= $_element->getHtmlId() ?>">
<?php endif; ?>
    <div class="hor-scroll">
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?= $this->escapeHtml($_element->getComment()) ?></p>
        <?php endif; ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?= $_element->getHtmlContent(); ?>
        <?php else: ?>
        <table cellspacing="0" class="<?= $_element->hasTableClass() ? $_element->getTableClass() : 'form-list'?>">
            <tbody>
                <?= $_element->getChildrenHtml(); ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
    <?= $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
    </ul>
<?php endif; ?>
</div>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif; ?>
