<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile
?>
<?php

$_product = $block->getProduct();
$sample_extensions = $this->helper('Ced\CsMarketplace\Helper\Data')->getStoreConfig('ced_vproducts/downloadable_config/sample_formats');
$supported_samples = explode(',', $sample_extensions);
?>

<div id="samples_container col-md-12">
    <h4 style="margin-bottom: 10px;" class="page-title col-md-12"><?= __('Samples') ?></h4>
    <div class="form-group col-md-6">
        <label><?= __('Title') ?>:</label>
        <div class="input-box">
            <input type="text" name="product[samples_title]" value="<?= $_product->getSamplesTitle() ?>"
                   id="samples_title" class="input-text form-control"/>
        </div>
    </div>
    <div style="clear:both;"></div>
    <br/>
    <div class="table-responsive col-md-12">
        <table cellspacing="0"
               class="data-table linearize-table-large sampletable table table-bordered table-hover table-striped"
               id="sample_table">
            <colgroup>
                <col/>
                <col/>
                <col/>
                <col width="1"/>
            </colgroup>
            <thead>
                <tr>
                    <th><label class="required"><em>*</em><?= __('Title'); ?></label></th>
                    <th><?= __('File'); ?></th>
                    <th class="nobr"><?= __('Sort Order'); ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="a-right" colspan="7">
                        <button class="sample_add_btn button btn btn-info btn-circle" type="button"
                                title="<?= __('Add New Row'); ?>">
                            <i class="fa  fa-plus"></i>
                        </button>
                    </td>
                </tr>
            </tfoot>
            <?php $j = 0;
            $productsamples = $block->getDownloadableProductSamples($_product);
            foreach ($productsamples as $productsample) {
                ?>
                <tbody class="sample_body">
                <tr>
                    <td data-rwd-label="<?= __('Title') ?>" class="number">
                        <input type="text" class="sample_title input-text input-text-large required-entry form-control"
                               value="<?= $productsample->getTitle() ?>"
                               name="downloadable[sample][<?= $j ?>][title]">
                        <input type="hidden" class="sample_id" value="<?= $productsample->getSampleId() ?>"
                               name="downloadable[sample][<?= $j ?>][sample_id]">
                    </td>

                    <td data-rwd-label="<?= __('File') ?>">
                        <ul style="list-style:none;padding: 0;text-align: left;">
                            <li>
                                <input type="radio" <?= $productsample->getSampleType() == 'file' ? 'checked="checked"' : '' ?>
                                       value='file' class='sample_type'
                                       name="downloadable[sample][<?= $j ?>][type]">
                                <label><?= __('File') ?>:</label>
                                <label class="label csbutton btn btn-circle btn-warning" for="sample<?= $j ?>"
                                       title="<?= __('Upload') ?>"><i class="fa  fa-upload "></i></label>
                                <input type="file" style="opacity:0; visibility:hidden; width:1px;height:1px;" id="sample<?= $j ?>" class="sample"
                                       name="samples[<?= $j ?>]">
                                <?php
                                $shortname = '';
                                $samplename = '';
                                if ($productsample->getSampleType() == 'file') {
                                    if ($samplename = $productsample->getSampleFile()) {
                                        $sample = explode('/', $samplename);
                                        if (isset($sample[1])) {
                                            $ext = explode('.', $sample[1]);
                                            if (isset($ext[1]))
                                                $shortname = substr($sample[1], 0, 4) . "..." . $ext[1];
                                            else
                                                $shortname = substr($sample[1], 0, 4) . "...";
                                        }
                                    } else {
                                        $shortname = __('No File Choosen');
                                        $samplename = __('No File Choosen');
                                    }
                                }

                                ?>
                                <span title="<?= $samplename; ?>"
                                      class="sample_name"><?= $shortname; ?></span>

                            </li>
                            <li style="padding-top: 2px;">
                                <input type="radio" value='url'
                                       class='sample_type' <?= $productsample->getSampleType() == 'url' ? 'checked="checked"' : '' ?>
                                       name="downloadable[sample][<?= $j ?>][type]">
                                <label><?= __('Url') ?>:</label>
                                <input type="text"
                                       data-validate="{'validate-downloadable-url':true}"
                                       class="sample_url form-control input-text input-text-large validate-url"
                                       value="<?= $productsample->getSampleUrl() ?>"
                                       name="downloadable[sample][<?= $j ?>][sample_url]">
                            </li>
                        </ul>
                    </td>
                    <td data-rwd-label="<?= __('Sort Order') ?>" class="number">
                        <input type="text" class="sample_sort_order input-text input-text-tiny form-control"
                               value="<?= $productsample->getSortOrder() ?>"
                               name="downloadable[sample][<?= $j ?>][sort_order]">
                    </td>

                    <td data-rwd-label="<?= __('Remove') ?>">
                        <span title="<?= __('Remove') ?>"
                                onclick="sampledelinkrow(this,'<?= $productsample->getSampleId() ?>');"
                                class="btn btn-danger btn-circle"><i class="fa fa-times"></i></span>
                    </td>

                </tr>
                </tbody>
                <?php $j++;
            } ?>
        </table>
    </div>
</div>
<script type="text/javascript">
    /* downloadable  product sample scripts */
    function sampledelinknewrow(elem) {
        jQuery(elem).parents(".sample_body").remove();
    }

    function sampledelinkrow(elem, id) {
        var dicisionapp = confirm('<?= __('Are you sure?') ?>');
        if (dicisionapp == true) {
            jQuery('#activity-loading').show();
            var link_id_val = jQuery(elem).parents(".sample_body").find('.sample_id').val();
            var links = jQuery('.sample_ids').val();
            var tot_link = link_id_val + "," + links;
            jQuery('.sample_ids').val(tot_link);
            jQuery.ajax({
                url: "<?= $block->getUrl('csmarketplace/vproducts/deleteSample', array('_nosid' => true));?>",
                type: "POST",
                data: {
                    sampleid: id,
                },
                dataType: 'html',
                success: function (content) {
                    if (content == 1) {
                        jQuery(this).parent('div').remove();
                        jQuery(elem).parents(".sample_body").remove();
                        alert("<?= __('Product Sample Successfully Deleted') ?>");
                    }
                    else
                        alert("<?= __('Error processing the request please Try Again') ?>");
                    jQuery('#activity-loading').hide();
                }
            });

        }
    }

    require([
        'jquery',
        'mage/mage',
        'mage/backend/validation'
    ], function(jced){
        var sample_row_count = <?= $j?>;

        jced.validator.addMethod(
            'ced-validate-downloadable-file', function (value,elem) {
               if (elem.parentNode.firstChild.checked) {
                   return (value !== '');
               } else {
                   return true;
               }
            }, jced.mage.__('File not uploaded.'));

        jced(".sample_add_btn").click(function () {
            var samplehtml = '<tbody class="sample_body">' +
                '<tr>' +
                '<td data-rwd-label="<?= __('Title') ?>" class="number">' +
                '<input type="text" class="sample_title input-text input-text-large required-entry form-control" name="downloadable[sample][' + sample_row_count + '][title]">' +
                '<input type="hidden" class="sample_id" name="downloadable[sample][' + sample_row_count + '][sample_id]">' +
                '</td>' +
                '<td data-rwd-label="<?= __('File') ?>">' +
                '<ul style="list-style:none;padding: 0;text-align: left;">' +
                '<li>' +
                '<input type="radio" data-id="'+sample_row_count+'" checked="checked" value="file" class="sample_type" name="downloadable[sample][' + sample_row_count + '][type]">' +
                '<label><?= __('File') ?>:</label>' +
                '<label class="label csbutton btn btn-circle btn-warning" for="sample' + sample_row_count + '" title="<?= __('Upload')?>"><i class="fa  fa-upload "></i></label>' +
                '<input type="file" data-validate="{\'ced-validate-downloadable-file\':true}" style="opacity:0; visibility:hidden; width:1px;height:1px;" id="sample' + sample_row_count + '" class="sample" name="samples[' + sample_row_count + ']">' +
                '<span class="sample_name"><?= __('No File Choosen') ?></span>' +
                '</li>' +
                '<li style="padding-top: 2px;">' +
                '<input type="radio" data-id="'+sample_row_count+'" value="url" class="sample_type" name="downloadable[sample][' + sample_row_count + '][type]">' +
                '<label><?= __('Url') ?>:</label>' +
                '<input data-validate="{\'validate-downloadable-url\':true}" type="text" id="sample_type_url'+sample_row_count+'" class="sample_url form-control input-text input-text-large validate-url form-control" name="downloadable[sample][' + sample_row_count + '][sample_url]">' +
                '</li>' +
                '</ul>' +
                '</td>' +
                '<td data-rwd-label="<?= __('Sort Order') ?>" class="number">' +
                '<input  class="sample_sort_order input-text input-text-tiny form-control" name="downloadable[sample][' + sample_row_count + '][sort_order]">' +
                '</td>' +
                '<td data-rwd-label="<?= __('Remove') ?>">' +
                '<span title="<?= __('Remove') ?>" onclick="sampledelinknewrow(this);" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></span>' +
                '</td>' +
                '</tr>' +
                '</tbody>';
            jced("#sample_table").append(samplehtml);
            sample_row_count++;
        });


        jced("body").delegate(".sample", "change", function () {
            var uploaded_file = jced(this).val();
            var extension = uploaded_file.split(".").pop();
            var extensions = <?= json_encode($supported_samples);?>;
            var maxFileSize = 2000000;

            if (extensions.indexOf(extension) < 0) {
                alert('Check File Type,\nAllowed file: <?= json_encode($supported_samples);?>');
                jced(this).val('');
            }
            else  if (this.files[0].size > maxFileSize) {
                alert('File size too large to upload.');
                jced(this).val('');
            } else{
                var samplename = uploaded_file.substr(0, 6) + "..." + uploaded_file.split('.').pop();
                jced(this).parent().children('.sample_name').text(samplename);
            }
        });
    });
</script>

