<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var $block \Ced\CsOrder\Block\Order\Creditmemo\View\Form */
$csOrderHelper = $block->getCsorderHelper();
$_order = $block->getCreditmemo()->getOrder();
$vorder = $block->getVendorOrder();
?>
<?= /* @noEscape */
$block->getChildHtml('order_info') ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">

        <?php if (!$_order->getIsVirtual()): ?>
        <div class="admin__page-section-item order-payment-method">
            <?php else: ?>
            <div class="admin__page-section-item order-payment-method order-payment-method-virtual">
                <?php endif; ?>
                <?php /* Billing Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @noEscape */
                        __('Payment Information') ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="order-payment-method-title"><?= /* @noEscape */
                        $block->getChildHtml('order_payment') ?></div>
                    <div class="order-payment-currency">
                        <?= /* @noEscape */
                        __('The order was placed using %1.', $_order->getOrderCurrencyCode())
                        ?>
                    </div>
                    <div class="order-payment-additional">
                        <?= /* @noEscape */
                        $block->getChildHtml('order_payment_additional'); ?>
                    </div>
                </div>
            </div>
            <?php
            if (is_object($vorder) && $csOrderHelper->canShowShipmentBlock($vorder)) {
                echo $block->getChildHtml('order_shipping_view');
            }
            ?>
        </div>
</section>
<?php $_items = $block->getCreditmemo()->getAllItems() ?>

<?php if (count($_items)): ?>
    <div id="creditmemo_items_container">
        <?= /* @noEscape */
        $block->getChildHtml('creditmemo_items') ?>
    </div>
<?php else: ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */
                __('Items Refunded') ?></span>
        </div>
        <div class="no-items admin__page-section-content"><?= /* @noEscape */
            __('No Items') ?></div>
    </section>
<?php endif; ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Memo Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Credit Memo History') ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= /* @noEscape */
                $block->getChildHtml('order_comments') ?></div>
        </div>
        <div class="admin__page-section-item order-totals" id="history_form">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Credit Memo Totals') ?></span>
            </div>
            <div class="admin__page-section-content"><?= /* @noEscape */
                $block->getChildHtml('creditmemo_totals') ?></div>
        </div>
    </div>
</section>
