<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php /** @var $block \Ced\CsOrder\Block\Order\View\Tab\History */ ?>
<section class="admin__page-section edit-order-comments">
    <ul class="note-list">
        <?php foreach ($block->getFullHistory() as $_item): ?>
            <li class="note-list-item">
                <span class="note-list-date"><?= /* @noEscape */
                    $block->getItemCreatedAt($_item) ?></span>
                <span class="note-list-time">
                <?= /* @noEscape */
                $block->getItemCreatedAt($_item, 'time') ?>
            </span>
                <span class="note-list-status"><?= /* @noEscape */
                    $block->getItemTitle($_item) ?></span>
                <?php if ($block->isItemNotified($_item, false)): ?>
                    <span class="note-list-customer">
                    <?= /* @noEscape */
                    __('Customer') ?>
                        <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                            <span class="note-list-customer-notapplicable">
                            <?= /* @noEscape */
                            __('Notification Not Applicable') ?>
                        </span>
                        <?php elseif ($block->isItemNotified($_item)): ?>
                            <span class="note-list-customer-notified">
                            <?= /* @noEscape */
                            __('Notified') ?>
                        </span>
                        <?php else: ?>
                            <span class="note-list-customer-not-notified">
                            <?= /* @noEscape */
                            __('Not Notified') ?>
                        </span>
                        <?php endif; ?>
                </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="edit-order-comments-block">
        <div class="edit-order-comments-block-title">
            <?= /* @noEscape */
            __('Notes for this Order') ?>
        </div>
        <?php foreach ($block->getFullHistory() as $_item): ?>
            <?php if ($_comment = $block->getItemComment($_item)): ?>
                <div class="comments-block-item">
                    <div class="comments-block-item-comment">
                        <?= /* @noEscape */
                        $_comment ?>
                    </div>
                    <span class="comments-block-item-date-time">
                        <?= /* @noEscape */
                        __('Comment added') ?>
                        <?= /* @noEscape */
                        $block->getItemCreatedAt($_item) ?>
                        <?= /* @noEscape */
                        $block->getItemCreatedAt($_item, 'time') ?>
                    </span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</section>
