<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var \Ced\CsOrder\Block\Order\View\Tab\Info $block */
$vorder = $block->getVOrder();
$_order = $block->getOrder();
?>

<div id="order-messages">
    <?= /* @noEscape */
    $block->getChildHtml('order_messages') ?>
</div>
<div class="page-main-actions">
    <?php
    //@codingStandardsIgnoreStart
    $vendorobj = $block->getVendor();
    $vendorEditUrl = $block->getUrl('csmarketplace/vendor/edit', ['vendor_id' => $vendorobj->getId()]);
    ?>
    <?= /* @noEscape */__('Vendor Name :') ?>
    <a href="<?= /* @noEscape */$vendorEditUrl ?>"><span style="padding-right: 5%;" class="title"><b>
                <?= /* @noEscape */__($vendorobj->getName()) ?></b></span></a>
    <?= /* @noEscape */__('Vendor Shop :') ?>
    <span style="padding-right: 5%;" class="title"><b><?= /* @noEscape */__($vendorobj->getShopUrl()) ?></b></span>
    <?= /* @noEscape */__('Public Name :') ?>
    <span style="padding-right: 5%;" class="title"><b><?= /* @noEscape */__($vendorobj->getPublicName()) ?></b></span>
</div>
<?= /* @noEscape */
$block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= /* @noEscape */
$_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?>
        order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= /* @noEscape */
                    $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency">
                    <?= /* @noEscape */
                    __('The order was placed using %1.', $_order->getOrderCurrencyCode())
                    ?>
                </div>
                <div class="order-payment-additional">
                    <?= /* @noEscape */
                    $block->getChildHtml('order_payment_additional'); ?>
                    <?= /* @noEscape */
                    $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?php
        if ($block->canShowShipmentBlock($vorder)) {
            echo $block->getChildHtml('order_shipping_view');
        }
        ?>
    </div>
</section>

<?= /* @noEscape */
$block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Items Ordered') ?></span>
    </div>
    <?= /* @noEscape */
    $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */
            __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Notes for this Order') ?></span>
            </div>
            <?= /* @noEscape */
            $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */
                    __('Order Totals') ?></span>
            </div>
            <?= /* @noEscape */
            $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= /* @noEscape */
$block->getChildHtml('popup_window'); ?>

<script>
    require([
        "prototype",
        "Magento_Sales/order/giftoptions_tooltip"
    ], function () {

//<![CDATA[
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0, 30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }

        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
        window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

    });
</script>
