<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals):?>
    <?php foreach ($_totals as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?= /* @noEscape */ $block->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?= /* @noEscape */ $_code?>">
            <td <?= /* @noEscape */ $block->getLabelProperties()?> class="a-right" colspan="3">
                <?php if ($_total->getStrong()):?>
                <?= /* @noEscape */ $_total->getLabel()?>
                <?php else:?>
                <?= /* @noEscape */ $_total->getLabel()?>
                <?php endif?>
            </td>
            <?php if ($_total->getStrong()):?>
            <td <?= /* @noEscape */ $block->getValueProperties()?> class=" a-right emph">
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php else:?>
            <td class="a-right" <?= /* @noEscape */ $block->getValueProperties()?>>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    
    <?php endif?>

    <?php $_totals = $block->getTotals('footer')?>
    <?php if ($_totals):?>
    <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?= /* @noEscape */ $block->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?= /* @noEscape */ $_code?>">
            <td <?= /* @noEscape */ $block->getLabelProperties()?> class="a-right" colspan="3">
                <?= /* @noEscape */ $_total->getLabel()?>
            </td>
            <td <?= /* @noEscape */ $block->getValueProperties()?> class="a-right">
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    <?php endif?>
