<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
// @codingStandardsIgnoreFile
?>
<?php $products = $block->getProducts(); ?>
<?php if(!empty($products)):?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;"
       summary="<?= __('Products') ?>">
    <thead>
    <tr>
        <th align="left" bgcolor="#EAEAEA"
            style="font-size: 13px; padding: 3px 9px"><?= __('Product Name') ?></th>
        <th align="left" bgcolor="#EAEAEA"
            style="font-size: 13px; padding: 3px 9px"><?= __('SKU') ?></th>
    </tr>
    </thead>
    <tbody bgcolor="#F6F6F6">
    <?php $i = 0; ?>
    <?php foreach ($products as $key => $product): ?>

        <tr align="left"
            style="font-size: 13px; padding: 3px 9px" <?= $i % 2 ? ' bgcolor="#EAEAEA"' : '#F6F6F6' ?> class="border">
            <td class="number"><?php if (isset($product['name'])) echo $product['name']; ?></td>
            <td class="number"><?php if (isset($product['sku'])) echo $product['sku']; ?></td>
        </tr>
        <?php $i++; ?>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
