<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_VendorsocialLogin
 * @author    CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php if ($block->_currentBlock->facebookEnabled()): ?>
    <div class="ced-sociallogin-login-facebook">
        <h3><?= $block->escapeHtml('Facebook Connect') ?></h3>
        <p><?= $block->escapeHtml('You can continue using your <strong>Facebook</strong> account.') ?></p>
        <?= $block->getChildHtml('ced_sociallogin_checkout_facebook_button'); ?>
    </div>
<?php endif; ?>
