<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$vendorData = $block->getVendorData();
if ($vendorData->getId()) {?>
    <div class="vendor-info"><?= /* @noEscape */ __('Vendor').' : ';?>
        <a href=<?= /* @noEscape */ $vendorData->getVendorShopUrl();?>><?= /* @noEscape */ $vendorData->getPublicName(); ?></a>
    </div>
<?php } ?>
<style>
    .vendor-info {
        margin-bottom: 8px;
        margin-top: 4px;
    }
</style>

