<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsOrder
 * @author     CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$vorder = $objectManager->create(\Magento\Framework\Registry::class)->registry('current_vorder');
$_order = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $block->getFullTaxInfo();
$taxHelper = $block->getData('taxHelper');
?>
<?php if ($vorder->getBaseTaxAmount()) { ?>
<tr>
    <td class="a-right" colspan="7">
        <div class="summary-collapse">
            <?php if ($taxHelper->displayFullSummary()): ?>
                <?= $block->escapeHtml(__('Total Tax')) ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('Tax')) ?>
            <?php endif;?>
        </div>
    </td>
    <td class="a-right last">
        <?= /* @noEscape */  $block->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php } ?>
</tr>
