name: "CI"

on:
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!
      - name: Add HTTP basic auth credentials
        run: composer config repositories.ced-csmarketplace composer https://marketplace:uCJM7117wkSIc2SZFtm4@repo.cedcommerce.com
      - uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs
          php_version: "8.1"
          env:
            COMPOSER_AUTH: '{"http-basic.repo.cedcommerce.com": {"username": "marketplace", "password": "uCJM7117wkSIc2SZFtm4"}}'

      - name: Composer install
        run: composer2 --version
