name: "CI"

on:
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!
      - uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Composer install
        run: |
          composer2 --version

      - uses: Novusvetus/action-php_codesniffer@1.2.13
        with:
          files: "**.php"
          scan_all: true
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
